export type GBRColor = "red" | "green" | "blue" | null;
export type GBRLens = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
export type GBRSubcategory = "mental_model" | "verbal" | "nonverbal" | "intention" | "role" | "structural";

export interface GBRElement {
  code: number;
  name: string;
  definition: string;
  lens: GBRLens;
  subcategory: GBRSubcategory;
  gbrColor: GBRColor;
}

export const GBR_TAXONOMY: GBRElement[] = [
  // ─── LENS 1 INFLUENCE ────────────────────────────────────────────────
  { code: 1101, name: "Influence Strategies", lens: 1, subcategory: "mental_model", gbrColor: null,
    definition: "The three main strategies people use to influence others in communication: domination (using force to win), manipulation (appealing to emotions with a hidden agenda), and conscious influence (being clear with intentions and respecting others)." },
  { code: 1103, name: "GreenBlueRed™", lens: 1, subcategory: "mental_model", gbrColor: null,
    definition: "A behavioral communication framework and coding language. Blue focuses on informing (focus on self), Green focuses on connecting and empathy (focus on other), and Red focuses on agreeing or common action (shared focus)." },
  { code: 1105, name: "Head-Up Display", lens: 1, subcategory: "mental_model", gbrColor: null,
    definition: "A mental model and visual lens used to step back, observe, and consciously evaluate the colors and levels of communication as they happen in real-time." },
  { code: 1201, name: "Advising", lens: 1, subcategory: "verbal", gbrColor: "red",
    definition: "A red verbal technique focused on giving constructive feedback and advice to others to drive action." },
  { code: 1202, name: "Red Question", lens: 1, subcategory: "verbal", gbrColor: "red",
    definition: "Leading inquiries or interrogations designed to guide or influence the other person towards a specific outcome or decision." },
  { code: 1203, name: "Suggesting", lens: 1, subcategory: "verbal", gbrColor: "red",
    definition: "A red verbal technique used for proposing an action, idea, or solution for common agreement." },
  { code: 1204, name: "Supporting", lens: 1, subcategory: "verbal", gbrColor: "red",
    definition: "A red verbal technique used to reassure people and redirect their efforts towards a shared goal." },
  { code: 1205, name: "Ordering", lens: 1, subcategory: "verbal", gbrColor: "red",
    definition: "A red verbal technique used for giving direct instructions, commands, or mandates." },
  { code: 1206, name: "Agreeing", lens: 1, subcategory: "verbal", gbrColor: "red",
    definition: "A red verbal technique used for expressing common grounds, aligning on decisions, and moving forward." },
  { code: 1304, name: "Red Rhythm", lens: 1, subcategory: "nonverbal", gbrColor: "red",
    definition: "A non-verbal behavior where a collective rhythm or deliberate pause is imposed on the group." },
  { code: 1305, name: "Red Timing", lens: 1, subcategory: "nonverbal", gbrColor: "red",
    definition: "A non-verbal behavior where the timing of communication is dictated by collective needs, schedules, or imposed deadlines." },
  { code: 1401, name: "Uniting", lens: 1, subcategory: "intention", gbrColor: "red",
    definition: "A red intention focused on connecting individuals and building a group into a cohesive team." },
  { code: 1402, name: "Seducing (Being Liked)", lens: 1, subcategory: "intention", gbrColor: "red",
    definition: "A red intention driven by the desire to be liked, to appeal to others, and to build charisma." },
  { code: 1403, name: "Fixing Problems", lens: 1, subcategory: "intention", gbrColor: "red",
    definition: "A red intention strictly focused on finding solutions, troubleshooting, and answering a brief together." },
  { code: 1404, name: "Changing Others", lens: 1, subcategory: "intention", gbrColor: "red",
    definition: "A red intention aimed at actively influencing, coaching, or modifying other people's behaviors." },
  { code: 1405, name: "Taking Over", lens: 1, subcategory: "intention", gbrColor: "red",
    definition: "A red intention involving the ability and willingness to step in and take control of a meeting, conversation, or process." },

  // ─── LENS 2 ATTITUDE ────────────────────────────────────────────────
  { code: 2101, name: "Attitude to Change", lens: 2, subcategory: "mental_model", gbrColor: null,
    definition: "A mental model describing four attitudes towards unplanned change: resisting (Type 0), doing (Type I), learning (Type II), and actively balancing learning with doing (Type III)." },
  { code: 2103, name: "Micro-Habits", lens: 2, subcategory: "mental_model", gbrColor: null,
    definition: "Small, conscious communication routines built on a behavioral loop of a trigger, an intention, an action/behavior, and a reward." },
  { code: 2401, name: "Attitude 0 (Resisting)", lens: 2, subcategory: "intention", gbrColor: null,
    definition: "An attitude that fears and resists change, says no, builds walls, and demonstrates low engagement." },
  { code: 2402, name: "Attitude I (Doing)", lens: 2, subcategory: "intention", gbrColor: null,
    definition: "An attitude that expects changing the world around you will change your experience; highly focused on problem-solving and outer action." },
  { code: 2403, name: "Attitude II (Learning)", lens: 2, subcategory: "intention", gbrColor: null,
    definition: "An attitude that expects internal change through learning and reflecting will change the world; driven by inner focus." },
  { code: 2404, name: "Attitude III (Growing)", lens: 2, subcategory: "intention", gbrColor: null,
    definition: "An attitude that actively and dynamically balances changing the world (doing) with changing oneself (learning)." },

  // ─── LENS 3 CHAORDIC ────────────────────────────────────────────────
  { code: 3101, name: "Chaordic Balance", lens: 3, subcategory: "mental_model", gbrColor: null,
    definition: "The state of balancing chaos (creative content and ideas) and order (structured process and rules) in a group to prevent wasted time and enable collective intelligence." },
  { code: 3102, name: "Algorithm Canvas", lens: 3, subcategory: "structural", gbrColor: null,
    definition: "Structured processes and meeting algorithms designed to help groups work together efficiently in collective intelligence." },
  { code: 3103, name: "Types of Conversation", lens: 3, subcategory: "mental_model", gbrColor: null,
    definition: "The four depths of communication: small talk/briefing, debates/discussions, negotiation/dialogue, and co-creation/presencing." },
  { code: 3105, name: "Framing", lens: 3, subcategory: "structural", gbrColor: null,
    definition: "The process of defining the purpose, rules, and timing at the start of a session to establish psychological safety and focus." },
  { code: 3111, name: "Chaordic Roles", lens: 3, subcategory: "role", gbrColor: null,
    definition: "Specific, neutral social roles (such as Host, Harvester, Steward) adopted to manage the group process and facilitate collective intelligence." },
  { code: 3112, name: "Participant / Expert", lens: 3, subcategory: "role", gbrColor: null,
    definition: "A content-focused role where an individual produces knowledge, shares ideas, and participates in the process based on their expertise." },
  { code: 3113, name: "Harvester", lens: 3, subcategory: "role", gbrColor: null,
    definition: "A chaordic process role focused on serving the group by listening, collecting, and crystallizing valuable outputs and collective intelligence." },
  { code: 3114, name: "Host", lens: 3, subcategory: "role", gbrColor: null,
    definition: "A chaordic process role focused on serving the group by holding time, maintaining rules, and keeping the psychological space safe without interfering with the content." },
  { code: 3115, name: "Steward", lens: 3, subcategory: "role", gbrColor: null,
    definition: "A meta-host role that looks after the long-term processes, rules, values, and structures across multiple meetings or projects." },

  // ─── LENS 4 FLOW ────────────────────────────────────────────────────
  { code: 4101, name: "Measuring Flow", lens: 4, subcategory: "mental_model", gbrColor: null,
    definition: "The process of tracking the mental state of optimal experience by mapping a person's perceived challenge against their perceived competence." },
  { code: 4102, name: "Conscious Feedback", lens: 4, subcategory: "mental_model", gbrColor: null,
    definition: "The interface of giving and receiving information (praise, advice, or opinions) to help individuals learn, adjust their flow state, and improve." },
  { code: 4103, name: "Motivation", lens: 4, subcategory: "mental_model", gbrColor: null,
    definition: "The internal drive that acts as the essential prerequisite and \"wind force\" needed to push an experience into a state of flow." },
  { code: 4104, name: "Challenge", lens: 4, subcategory: "mental_model", gbrColor: null,
    definition: "The self-perceived level of difficulty or stress inherent in a task or communication situation." },
  { code: 4105, name: "Skill (Competence)", lens: 4, subcategory: "mental_model", gbrColor: null,
    definition: "The self-perceived level of ability, knowledge, or confidence an individual has in a given situation." },

  // ─── LENS 5 ALIGNMENT ───────────────────────────────────────────────
  { code: 5101, name: "Alignment", lens: 5, subcategory: "mental_model", gbrColor: null,
    definition: "The internal congruence between what a person is doing, saying, thinking, and feeling during a conflict or communication." },
  { code: 5102, name: "Congruence", lens: 5, subcategory: "mental_model", gbrColor: null,
    definition: "The state where a person's verbal techniques, non-verbal behaviors, and underlying intentions perfectly match and align, building trust." },
  { code: 5103, name: "Meaning", lens: 5, subcategory: "mental_model", gbrColor: null,
    definition: "The psychological unlocking factor based on logotherapy, which asserts that the meaning an individual assigns to an event dictates their reality and healing." },
  { code: 5105, name: "Presencing", lens: 5, subcategory: "mental_model", gbrColor: null,
    definition: "A deep level of conversation where one holds space for another without judgment, acting as an empathic mirror to help them think out loud and reflect." },
  { code: 5201, name: "Positive Phrases", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "A green verbal technique used to share factual praise, give credits of intention, and establish a trusting foundation." },
  { code: 5202, name: "Green Questions", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "Open-ended questions (like what, how, why, when) used to navigate another's mind and understand them with curiosity and empathy." },
  { code: 5203, name: "Mirroring", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "A green verbal technique used to reflect the other person's situation, tone, or words back to them to help them feel seen and understood." },
  { code: 5204, name: "Summarising", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "A green verbal technique where what was said is re-expressed briefly with keywords to align understanding and ensure the speaker feels heard." },
  { code: 5205, name: "Accusation Audit", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "A green verbal technique that lowers defensiveness by preemptively listing the negative assumptions or complaints the other person might be harboring." },
  { code: 5206, name: "Unlocking", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "A green verbal technique used in negotiation to open new avenues for problem-solving (e.g., \"Under what circumstances would you be prepared to...?\")." },
  { code: 5207, name: "Labelling", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "An advanced green verbal technique where the listener reformulates and names the underlying feeling or emotion of the speaker." },
  { code: 5208, name: "Elephant", lens: 5, subcategory: "verbal", gbrColor: "green",
    definition: "A green verbal technique that involves voicing an obvious but unspoken collective situation factually, respectfully, and without personal judgment." },
  { code: 5301, name: "Green Silence", lens: 5, subcategory: "nonverbal", gbrColor: "green",
    definition: "A non-verbal behavior characterized by active listening, where silence is deliberately used to focus entirely on understanding the other person." },
  { code: 5303, name: "Green Body-Language", lens: 5, subcategory: "nonverbal", gbrColor: "green",
    definition: "Open, adaptable, and respectful non-verbal posturing focused on making the other person feel comfortable and safe." },
  { code: 5304, name: "Green Rhythm", lens: 5, subcategory: "nonverbal", gbrColor: "green",
    definition: "A non-verbal behavior where one actively adapts, paces, and reacts to the other person's natural conversational rhythm." },
  { code: 5305, name: "Green Timing", lens: 5, subcategory: "nonverbal", gbrColor: "green",
    definition: "A non-verbal behavior involving choosing a time to communicate that is most considerate, convenient, and suitable for the other person." },
  { code: 5402, name: "Respect", lens: 5, subcategory: "intention", gbrColor: "green",
    definition: "A green intention centered on being entirely okay with others having different opinions, needs, values, and beliefs without judging them." },
  { code: 5403, name: "Building Trust", lens: 5, subcategory: "intention", gbrColor: "green",
    definition: "A green intention focused deliberately on building bridges, establishing rapport, and creating a safe connection." },
  { code: 5404, name: "Empathy", lens: 5, subcategory: "intention", gbrColor: "green",
    definition: "A green intention focused on putting oneself in the other person's shoes to genuinely understand their emotional and factual experience." },
  { code: 5405, name: "Curiosity", lens: 5, subcategory: "intention", gbrColor: "green",
    definition: "A green intention driven by a yearning to understand, allowing information to come from the other person without imposing one's own assumptions." },
  { code: 5406, name: "Agape", lens: 5, subcategory: "intention", gbrColor: "green",
    definition: "A green intention representing the highest form of selfless, unconditional love and connection without expecting anything in return." },

  // ─── LENS 6 NEEDS ───────────────────────────────────────────────────
  { code: 6101, name: "Chakra Needs", lens: 6, subcategory: "mental_model", gbrColor: null,
    definition: "A mental model that categorizes human needs into an easy-to-navigate hierarchy (physical, abundance, autonomy, connection, expression, meaning, peace)." },
  { code: 6104, name: "Functional Conflicts", lens: 6, subcategory: "mental_model", gbrColor: null,
    definition: "Disagreements focused on tasks or processes that successfully build trust and collective intelligence, as opposed to dysfunctional conflicts focused on ego." },
  { code: 6105, name: "Types of Love", lens: 6, subcategory: "mental_model", gbrColor: null,
    definition: "A mental model utilizing the 8 types of Greek love to more accurately understand the deep drivers and motivations behind human connections." },
  { code: 6106, name: "Stages of Team", lens: 6, subcategory: "mental_model", gbrColor: null,
    definition: "A mental model outlining the five developmental stages of team formation: forming, storming, norming, performing, and adjourning." },
  { code: 6201, name: "Conscious Request", lens: 6, subcategory: "verbal", gbrColor: null,
    definition: "The practice of formulating needs into requests that are open, positive, concrete, measurable, realistic, and immediate." },
  { code: 6402, name: "Storge", lens: 6, subcategory: "intention", gbrColor: null,
    definition: "Infinite, familiar love built upon acceptance, deep emotional connection, and long-term mutual respect." },
  { code: 6403, name: "Mania", lens: 6, subcategory: "intention", gbrColor: null,
    definition: "Manic, obsessive, or codependent love often characterized by possession or jealousy." },
  { code: 6404, name: "Eros", lens: 6, subcategory: "intention", gbrColor: null,
    definition: "Sensual and passionate love that displays affection, attraction, and seeks sexual or physical fulfillment." },
  { code: 6405, name: "Philia", lens: 6, subcategory: "intention", gbrColor: null,
    definition: "Friendship or brotherly love based on mutual respect, joint interests, and common values without romantic feelings." },
  { code: 6406, name: "Ludus", lens: 6, subcategory: "intention", gbrColor: null,
    definition: "Flirtatious, playful, and child-like love that engages in activities to make people feel alive and excited." },

  // ─── LENS 7 EGO ─────────────────────────────────────────────────────
  { code: 7101, name: "Ego Triggers", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "Internal emotional reactions that occur when an individual compares themselves to others on a physical, emotional, intellectual, or spiritual level." },
  { code: 7102, name: "Drama Triangle", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "The Karpman triangle detailing the dysfunctional, conflict-prone relationship roles of victim, savior, and aggressor." },
  { code: 7103, name: "Expressing", lens: 7, subcategory: "nonverbal", gbrColor: null,
    definition: "The non-verbal behavior of openly displaying one's own emotions, thoughts, and feelings from the heart." },
  { code: 7104, name: "Consciousness Barrier", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "The internal obstacle of knowing your own values, beliefs, and true intentions before attempting to communicate them to someone else." },
  { code: 7105, name: "Permission Barrier", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "The obstacle of feeling authorised to communicate, driven by either internal self-worth or external hierarchical authority." },
  { code: 7106, name: "Sensorial Barrier", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "The obstacle of getting a message heard through the noise of information overload by effectively utilising multiple human senses." },
  { code: 7107, name: "Language Barrier", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "The obstacle of being understood across different spoken languages, technical jargon, or differing interpretations of words." },
  { code: 7108, name: "Tangibility Barrier", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "The obstacle of making communication concrete and memorable enough that the analytical brain can easily grasp and recall the meaning." },
  { code: 7109, name: "Ego Hats", lens: 7, subcategory: "mental_model", gbrColor: null,
    definition: "The various unofficial social identities and behavioral roles individuals unconsciously swap between during work communication." },
  { code: 7113, name: "Devil's Advocate", lens: 7, subcategory: "role", gbrColor: null,
    definition: "An ego role that reveals important assumptions but can create chaos and friction by being overly pessimistic or making wrong assumptions." },
  { code: 7114, name: "Hero", lens: 7, subcategory: "role", gbrColor: null,
    definition: "An ego role that bravely solves problems with creative solutions but can waste the group's time by creating imaginary problems to solve." },
  { code: 7115, name: "Narrator / Joker", lens: 7, subcategory: "role", gbrColor: null,
    definition: "An ego role that mirrors group insights through storytelling and humor, but can waste time by gossiping or losing focus." },
  { code: 7116, name: "Hermit / Monk", lens: 7, subcategory: "role", gbrColor: null,
    definition: "An ego role that lets people speak and asks big-picture questions, but can easily become withdrawn, lazy, or passive." },
  { code: 7117, name: "Artisan", lens: 7, subcategory: "role", gbrColor: null,
    definition: "An ego role that helps the group build solutions through detailed dialogue, but can easily get bogged down and stuck in the minutiae." },
  { code: 7201, name: "Informing", lens: 7, subcategory: "verbal", gbrColor: "blue",
    definition: "A blue verbal technique focused on sharing new facts, knowledge, or information that belongs strictly to the speaker." },
  { code: 7202, name: "Blue Question", lens: 7, subcategory: "verbal", gbrColor: "blue",
    definition: "A closed, leading, or opinionated question designed to validate the speaker's own assumptions rather than explore the other's mind." },
  { code: 7203, name: "Judging", lens: 7, subcategory: "verbal", gbrColor: "blue",
    definition: "A blue verbal technique used to explicitly share one's own opinions, evaluations, and value-based judgments." },
  { code: 7204, name: "Projecting", lens: 7, subcategory: "verbal", gbrColor: "blue",
    definition: "A blue verbal technique that involves planning future actions, forecasting, or projecting one's own thoughts and feelings onto another person." },
  { code: 7205, name: "Apologising", lens: 7, subcategory: "verbal", gbrColor: "blue",
    definition: "A blue verbal technique used to take accountability, express regret, and manage conflicts." },
  { code: 7206, name: "Storytelling", lens: 7, subcategory: "verbal", gbrColor: "blue",
    definition: "A blue verbal technique that utilises engaging narratives to cross the tangibility barrier and make information memorable." },
  { code: 7301, name: "Blue Silence", lens: 7, subcategory: "nonverbal", gbrColor: "blue",
    definition: "A non-verbal behavior where a person focuses entirely inward, getting lost in their own thoughts or zoning out of the conversation." },
  { code: 7303, name: "Blue Body-Language", lens: 7, subcategory: "nonverbal", gbrColor: "blue",
    definition: "Non-verbal posturing focused entirely on the speaker's own physical comfort, space, and self-expression." },
  { code: 7304, name: "Blue Rhythm", lens: 7, subcategory: "nonverbal", gbrColor: "blue",
    definition: "A non-verbal behavior where a person communicates solely according to their own internal pace and speed, ignoring the group's pace." },
  { code: 7305, name: "Blue Timing", lens: 7, subcategory: "nonverbal", gbrColor: "blue",
    definition: "A non-verbal behavior where a person communicates at a time that suits them personally, regardless of the other person's readiness or convenience." },
  { code: 7401, name: "Learning", lens: 7, subcategory: "intention", gbrColor: "blue",
    definition: "A blue intention driven by a self-focused desire to acquire knowledge, understand theories, and grow oneself." },
  { code: 7402, name: "Pragmatism", lens: 7, subcategory: "intention", gbrColor: "blue",
    definition: "A blue intention focused heavily on achieving practical results, efficiency, and getting tasks done logically." },
  { code: 7403, name: "Philautia", lens: 7, subcategory: "intention", gbrColor: "blue",
    definition: "A blue intention representing self-compassion, self-care, and the fulfilment of one's own needs before attempting to help others." },
  { code: 7404, name: "Ego", lens: 7, subcategory: "intention", gbrColor: "blue",
    definition: "A blue intention driven by the internal need to build one's own self-confidence, status, and receive recognition or validation." },
  { code: 7405, name: "Gratitude", lens: 7, subcategory: "intention", gbrColor: "blue",
    definition: "A blue intention focused on internally feeling and openly expressing thankfulness and appreciation." },
  { code: 7406, name: "Responsibilities", lens: 7, subcategory: "intention", gbrColor: "blue",
    definition: "A blue intention where an individual focuses on acknowledging, owning, and facing their own duties and obligations." },

  // ─── LENS 8 DYNAMICS ────────────────────────────────────────────────
  { code: 8101, name: "Relationship Dynamics", lens: 8, subcategory: "mental_model", gbrColor: null,
    definition: "The measurement of how communication polarity flows between individuals, categorising relations as vertical, horizontal, or dynamically balanced." },
  { code: 8103, name: "Yin Yang Polarity", lens: 8, subcategory: "mental_model", gbrColor: null,
    definition: "The dynamic, shifting balance of leading (Yang) and following (Yin) in healthy interpersonal communication." },
];

export function getGBRElement(code: number): GBRElement | undefined {
  return GBR_TAXONOMY.find(el => el.code === code);
}

export function getGBRColor(code: number): GBRColor {
  return getGBRElement(code)?.gbrColor ?? null;
}

export function getGBRDefinition(code: number): string | undefined {
  return getGBRElement(code)?.definition;
}

export const GBR_COLOR_LABELS: Record<NonNullable<GBRColor>, string> = {
  red: "Red — shared focus",
  green: "Green — other focus",
  blue: "Blue — self focus",
};

export const GBR_COLOR_HEX: Record<NonNullable<GBRColor>, string> = {
  red: "#cc3333",
  green: "#339966",
  blue: "#3399cc",
};
