// French editorial draft. Public routing and indexing await the bilingual-shell batch.
import { renderReadableAcx } from './acx-readable';
export const ACX_ARTICLE_FR = {
  "language": "fr",
  "status": "draft_for_review",
  "title": "Les quatre niveaux ACX : un guide pratique pour travailler avec l’IA",
  "description": "Découvrez les quatre niveaux ACX : échanger avec l’IA, relier les tâches et travailler en équipe. Exemples simples et formations centrées sur l’humain."
} as const;

const ORIGINAL_ARTICLE_FR_HTML = `<header class="acx-article-header">
<p class="acx-kicker">Comprendre l’IA · Guide pratique</p>
<h1>Les quatre niveaux ACX : un guide pratique pour travailler avec l’IA</h1>
<p class="acx-deck">De votre premier échange avec l’IA au travail en équipe. Découvrez ce qui change, ce que vous pouvez pratiquer et où votre jugement reste essentiel.</p>
<p class="acx-byline">Par Estève Pannetier · Coach en communication avec l’IA</p>
<p class="acx-draft">Adaptée de mon article LinkedIn du 9 janvier 2026</p>
</header>
<div class="acx-reading-layout">
<aside class="acx-toc"><nav aria-label="Sommaire de l’article"><h2>Dans ce guide</h2><div class="acx-toc-groups"><div class="acx-toc-levels"><h3>Les quatre niveaux</h3><ol><li><a href="#acx-1"><span class="acx-tag" data-acx-level="1"><img src="/images/acx/acx-1-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>1 · Échanger</span></span></a></li><li><a href="#acx-2"><span class="acx-tag" data-acx-level="2"><img src="/images/acx/acx-2-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>2 · Relier</span></span></a></li><li><a href="#acx-3"><span class="acx-tag" data-acx-level="3"><img src="/images/acx/acx-3-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>3 · Guider</span></span></a></li><li><a href="#acx-4"><span class="acx-tag" data-acx-level="4"><img src="/images/acx/acx-4-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>4 · Coordonner</span></span></a></li></ol></div><div class="acx-toc-context"><h3>Les repères</h3><a href="#acx-meaning">Qu’est-ce qu’ACX ?</a><a href="#acx-human-skills">Partir des compétences humaines</a><a href="#acx-connections">Qui communique avec qui ?</a><h3>Mettre en pratique</h3><a href="#acx-practice">Essayer un exercice</a><a href="#acx-scan">La place du Scan</a><a href="#acx-training">Choisir votre formation</a></div></div></nav></aside>
<div class="acx-reading-body">
<section id="acx-meaning"><h2>Quels sont les quatre niveaux ACX ?</h2>
<p><strong>ACX est mon guide pour comprendre quatre façons de travailler avec l’IA : les échanges personnels, les tâches reliées, les assistants IA et le travail entre membres d’une équipe.</strong> Plus les outils et les personnes sont nombreux, plus les consignes, les passages de relais et les vérifications humaines comptent.</p>
<p>ACX est né de mes recherches sur l’IA et la communication avec <a href="https://www.arbora.partners/research" target="_blank" rel="noopener noreferrer">Arbora</a>. J’en propose ici une synthèse pratique : relier ces idées pour aider chacun à choisir en conscience comment utiliser l’IA.</p><aside class="acx-position"><h3>Les personnes choisissent la direction</h3><p>Mon approche est centrée sur l’humain. Garder notre pouvoir d’agir et notre souveraineté, c’est choisir les objectifs, poser des limites et pouvoir questionner ou arrêter ce que fait l’IA. Le but est un usage intelligent et conscient, pas l’automatisation à tout prix.</p></aside>
<details class="acx-origin"><summary>Pourquoi l’image des vitesses ?</summary><p>J’ai d’abord expliqué cette idée avec des schémas sur des serviettes en papier, lors d’un déjeuner près de la gare de Zurich. La question était simple : que se passe-t-il quand l’IA crée plus d’échanges que nous ne pouvons en suivre ?</p>
<p>J’ai pris l’image des vitesses d’une voiture. En première, vous gardez un contrôle direct. Les vitesses suivantes permettent d’aller plus loin, mais demandent une autre attention. Cette image aide à apprendre ; elle ne sert pas à noter une personne ou une équipe.</p></details>
<p>Pour apprendre à utiliser l’IA, la bonne question est : <em>que dois-je comprendre et vérifier à ce niveau ?</em></p>
<div id="acx-overview" class="acx-table-wrap" role="region" aria-label="Les niveaux ACX en bref" tabindex="0"><table><caption>Les quatre niveaux en bref</caption><thead><tr><th scope="col">Niveau</th><th scope="col">Ce qui change</th><th scope="col">Votre rôle</th></tr></thead><tbody><tr><th scope="row"><a href="#acx-1" class="acx-tag" data-acx-level="1"><img src="/images/acx/acx-1-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>1 · Échanger</span></a></th><td>Vous travaillez directement avec un outil d’IA.</td><td>Fixer l’objectif et vérifier la réponse.</td></tr><tr><th scope="row"><a href="#acx-2" class="acx-tag" data-acx-level="2"><img src="/images/acx/acx-2-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>2 · Relier</span></a></th><td>Le travail passe d’un outil ou d’une personne à l’autre.</td><td>Vérifier ce qui est transmis et désigner un responsable.</td></tr><tr><th scope="row"><a href="#acx-3" class="acx-tag" data-acx-level="3"><img src="/images/acx/acx-3-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>3 · Guider</span></a></th><td>Un assistant IA enchaîne plusieurs étapes.</td><td>Fixer des limites, des points de contrôle et un moyen d’arrêter.</td></tr><tr><th scope="row"><a href="#acx-4" class="acx-tag" data-acx-level="4"><img src="/images/acx/acx-4-outline.svg" width="22" height="22" alt="" aria-hidden="true"><span>4 · Coordonner</span></a></th><td>Les membres d’une équipe travaillent avec l’IA.</td><td>Convenir des rôles, du partage et des décisions finales.</td></tr></tbody></table></div></section>
<section id="acx-human-skills"><h2>Avant les outils : penser, dire, agir et ressentir</h2><figure class="acx-drawing"><a class="acx-drawing-image" href="/images/acx/think-say-do-feel-colour-original.jpg" target="_blank" rel="noopener noreferrer" aria-label="Agrandir le dessin dans un nouvel onglet"><img src="/images/acx/think-say-do-feel-colour-original.jpg" width="3504" height="2480" loading="lazy" decoding="async" alt="Dessin à la main d’Estève : penser, dire, ressentir et agir, dans le contexte qui entoure la personne."></a><figcaption>Dessin original d’Estève Pannetier. Les mots anglais sont expliqués dans le texte ci-dessous. <a href="/images/acx/think-say-do-feel-colour-original.jpg" target="_blank" rel="noopener noreferrer">Agrandir ↗</a></figcaption></figure>
<p>Un prompt clair commence avant la première phrase. Vous devez savoir ce que vous cherchez, ce que vous savez et ce qui reste incertain. Un prompt, c’est la consigne que vous donnez à l’IA.</p>
<p>Le <a href="/periodic-table">Tableau périodique de la communication consciente</a> nous aide à regarder quatre dimensions de la communication humaine :</p>
<ul><li><strong>Penser et comprendre :</strong> quel est mon objectif ? Quelles informations pourraient me faire changer d’avis ?</li>
<li><strong>Dire et écrire :</strong> donnez des consignes claires à l’IA. Vérifiez le sens et le ton de ses textes. Gardez votre voix et pensez à la personne qui vous lit.</li>
<li><strong>Agir et communiquer sans mots :</strong> utilisez l’IA pour préparer le bon moment, le rythme et les pauses. Choisissez quand parler, attendre ou relancer. Le langage du corps compte aussi lorsque vous rencontrez les autres.</li>
<li><strong>Ressentir et clarifier son intention :</strong> communiquer en conscience, c’est aussi formuler ses prompts en conscience. Reconnaissez ce que vous ressentez et clarifiez votre intention dans chaque échange avec l’IA.</li></ul>
<p>Avec les agents IA, on peut vite ne penser qu’aux mots. Pourtant, le moment d’un message, l’espace entre les réponses et la fréquence des relances façonnent aussi la conversation. Demandez à l’IA de vous aider à préparer ce rythme, puis choisissez ce qui convient aux personnes concernées.</p>
<p>L’IA peut vous aider à explorer une idée. Elle ne peut pas savoir avec certitude ce qu’une autre personne pense ou ressent. Continuez à lui poser la question plutôt que de prendre une supposition de l’IA pour sa réponse.</p></section>
<section id="acx-connections"><h2>Qui communique avec qui ?</h2><p>Ces quatre repères aident à suivre un travail. Ils décrivent des échanges, pas quatre niveaux ACX séparés.</p>
<dl class="acx-definitions"><div><dt><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-brain" aria-hidden="true" focusable="false"><path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"></path><path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"></path><path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4"></path><path d="M17.599 6.5a3 3 0 0 0 .399-1.375"></path><path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"></path><path d="M3.477 10.896a4 4 0 0 1 .585-.396"></path><path d="M19.938 10.5a4 4 0 0 1 .585.396"></path><path d="M6 18a4 4 0 0 1-1.967-.516"></path><path d="M19.967 17.484A4 4 0 0 1 18 18"></path></svg> H2S · De soi à soi</dt><dd>Vous réfléchissez à votre objectif, à vos ressentis et à vos suppositions. Cette réflexion prépare votre prompt.</dd></div><div><dt><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-messages-square" aria-hidden="true" focusable="false"><path d="M14 9a2 2 0 0 1-2 2H6l-4 4V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2z"></path><path d="M18 9h2a2 2 0 0 1 2 2v11l-4-4h-6a2 2 0 0 1-2-2v-1"></path></svg> HAI · De l’humain à l’IA</dt><dd>Vous formulez une demande, lisez la réponse et posez des questions complémentaires.</dd></div><div><dt><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-network" aria-hidden="true" focusable="false"><rect x="16" y="16" width="6" height="6" rx="1"></rect><rect x="2" y="16" width="6" height="6" rx="1"></rect><rect x="9" y="2" width="6" height="6" rx="1"></rect><path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"></path><path d="M12 12V8"></path></svg> A2A · D’une IA à une autre</dt><dd>Des outils d’IA se transmettent des informations ou des tâches. Les personnes décident ce qui peut être partagé et comment vérifier le résultat.</dd></div><div><dt><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users" aria-hidden="true" focusable="false"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg> H2H · Entre personnes</dt><dd>Vous écoutez, expliquez, exprimez un désaccord et décidez avec les autres. Une réponse d’IA peut nourrir la conversation ; elle ne la remplace pas.</dd></div></dl>
<details class="acx-note"><summary>À propos de ces sigles</summary><p>H2S et HAI sont les repères choisis dans ce guide. Vous rencontrerez peut-être d’autres termes ailleurs. A2A désigne aussi le <a href="https://a2a-protocol.org/latest/" target="_blank" rel="noopener noreferrer">protocole Agent2Agent</a>, une norme technique précise pour les échanges entre agents IA. Ici, A2A désigne plus largement les échanges entre IA ; cela ne signifie pas qu’un outil utilise ce protocole.</p></details><details class="acx-original-detail"><summary>Voir le dessin original des échanges humains</summary><figure class="acx-drawing"><a class="acx-drawing-image" href="/images/acx/think-say-do-feel-original.png" target="_blank" rel="noopener noreferrer" aria-label="Agrandir le dessin dans un nouvel onglet"><img src="/images/acx/think-say-do-feel-original.png" width="1920" height="1080" loading="lazy" decoding="async" alt="Schéma original : les pensées et ressentis de A, ses paroles et actions, et ses échanges avec B."></a><figcaption>Dessin original d’Estève Pannetier, conservé en anglais. <a href="/images/acx/think-say-do-feel-original.png" target="_blank" rel="noopener noreferrer">Agrandir ↗</a></figcaption></figure></details></section>
<aside class="acx-source-note"><p>Les dessins d’origine utilisent H2A là où ce guide dit HAI. Leur niveau 4 montre une réflexion plus large sur la gouvernance et l’infrastructure. La formation présentée ici reste centrée sur les échanges entre membres d’une équipe.</p></aside>
<section id="acx-1"><p class="acx-kicker">Première vitesse</p><h2>Niveau ACX 1 : apprendre à échanger avec l’IA</h2><div class="acx-level-heading" data-acx-level="1"><span class="acx-level-icon"><img src="/images/acx/acx-1-outline.svg" width="80" height="80" alt="" aria-hidden="true"></span><div><span class="acx-level-label">ACX 1</span><p>Demander et vérifier</p></div></div>
<p>Vous demandez de l’aide à un outil d’IA pour une tâche. Vous restez proche de chaque étape : écrire, lire, vérifier et reprendre.</p>
<p><strong>Exemple :</strong> vous devez expliquer un retard à un client. Notez d’abord ce qui s’est passé et votre objectif. Demandez un brouillon à l’IA avec des noms fictifs. Vérifiez les faits, le ton et les promesses avant de reprendre une seule phrase.</p>
<p>L’échange commence par H2S : mettre vos idées au clair. Il passe à HAI lorsque vous envoyez le prompt. Quand vous parlez au client, H2H reprend sa place.</p>
<div class="acx-practice"><h3>Votre vérification en première vitesse</h3><p>Puis-je expliquer pourquoi j’ai gardé chaque partie de cette réponse ? Sinon, je dois la relire.</p></div><figure class="acx-drawing"><a class="acx-drawing-image" href="/images/acx/acx-1-original.png" target="_blank" rel="noopener noreferrer" aria-label="Agrandir le dessin dans un nouvel onglet"><img src="/images/acx/acx-1-original.png" width="1920" height="1080" loading="lazy" decoding="async" alt="Dessin original du niveau ACX 1, avec les connexions concernées mises en couleur."></a><figcaption>ACX 1 · Dessin original d’Estève Pannetier. Textes et périmètre d’origine conservés. <a href="/images/acx/acx-1-original.png" target="_blank" rel="noopener noreferrer">Agrandir ↗</a></figcaption></figure><a class="acx-back" href="#acx-overview">↑ Retour aux quatre niveaux</a></section>
<section id="acx-2"><p class="acx-kicker">Deuxième vitesse</p><h2>Niveau ACX 2 : relier les étapes sans perdre le contexte</h2><div class="acx-level-heading" data-acx-level="2"><span class="acx-level-icon"><img src="/images/acx/acx-2-outline.svg" width="80" height="80" alt="" aria-hidden="true"></span><div><span class="acx-level-label">ACX 2</span><p>Relier les étapes</p></div></div>
<p>Un brouillon passe maintenant par plusieurs étapes. Un workflow est simplement une suite de tâches reliées. Certaines font appel à l’IA ; d’autres demandent l’intervention d’une personne.</p>
<p><strong>Exemple :</strong> un outil transforme des notes de réunion approuvées en liste d’actions. Un autre compare cette liste aux notes. Un collègue la relit avant que des tâches soient attribuées.</p>
<p>Cela ajoute des échanges entre outils, parfois entre IA. Surveillez le passage de relais : qu’est-ce qui a été oublié, modifié ou supposé ? Un résumé bien rédigé peut passer à côté de l’essentiel.</p>
<div class="acx-practice"><h3>Votre vérification en deuxième vitesse</h3><p>Désignez la personne responsable du résultat. Gardez les notes d’origine accessibles. Décidez de ce qui doit être vérifié avant l’étape suivante.</p></div><figure class="acx-drawing"><a class="acx-drawing-image" href="/images/acx/acx-2-original.png" target="_blank" rel="noopener noreferrer" aria-label="Agrandir le dessin dans un nouvel onglet"><img src="/images/acx/acx-2-original.png" width="1920" height="1080" loading="lazy" decoding="async" alt="Dessin original du niveau ACX 2, avec les connexions concernées mises en couleur."></a><figcaption>ACX 2 · Dessin original d’Estève Pannetier. Textes et périmètre d’origine conservés. <a href="/images/acx/acx-2-original.png" target="_blank" rel="noopener noreferrer">Agrandir ↗</a></figcaption></figure><a class="acx-back" href="#acx-overview">↑ Retour aux quatre niveaux</a></section>
<section id="acx-3"><p class="acx-kicker">Troisième vitesse</p><h2>Niveau ACX 3 : guider un assistant IA avec des limites claires</h2><div class="acx-level-heading" data-acx-level="3"><span class="acx-level-icon"><img src="/images/acx/acx-3-outline.svg" width="80" height="80" alt="" aria-hidden="true"></span><div><span class="acx-level-label">ACX 3</span><p>Guider l’agent</p></div></div>
<p>Un agent est un outil d’IA qui peut enchaîner plusieurs étapes vers un objectif. Au lieu d’écrire chaque consigne, vous fixez la tâche, les limites et les points de contrôle.</p>
<p><strong>Exemple :</strong> un assistant IA prépare une note à partir de documents approuvés. Il peut proposer des questions à éclaircir. Une personne vérifie les sources et décide de ce qui sera partagé. Envoyer des messages ou prendre des engagements demande une autorisation distincte.</p>
<p>L’assistant peut utiliser d’autres outils. Des consignes claires et un suivi visible deviennent alors encore plus utiles. Une réponse fluide ne prouve pas que l’outil a compris votre équipe.</p>
<div class="acx-practice"><h3>Votre vérification en troisième vitesse</h3><p>Que peut faire cet assistant ? Quand doit-il demander ? Comment puis-je l’arrêter et revoir ce qui s’est passé ?</p></div><figure class="acx-drawing"><a class="acx-drawing-image" href="/images/acx/acx-3-original.png" target="_blank" rel="noopener noreferrer" aria-label="Agrandir le dessin dans un nouvel onglet"><img src="/images/acx/acx-3-original.png" width="1920" height="1080" loading="lazy" decoding="async" alt="Dessin original du niveau ACX 3, avec les connexions concernées mises en couleur."></a><figcaption>ACX 3 · Dessin original d’Estève Pannetier. Textes et périmètre d’origine conservés. <a href="/images/acx/acx-3-original.png" target="_blank" rel="noopener noreferrer">Agrandir ↗</a></figcaption></figure><a class="acx-back" href="#acx-overview">↑ Retour aux quatre niveaux</a></section>
<section id="acx-4"><p class="acx-kicker">Quatrième vitesse</p><h2>Niveau ACX 4 : travailler avec l’IA entre membres d’une équipe</h2><div class="acx-level-heading" data-acx-level="4"><span class="acx-level-icon"><img src="/images/acx/acx-4-outline.svg" width="80" height="80" alt="" aria-hidden="true"></span><div><span class="acx-level-label">ACX 4</span><p>Travailler en équipe</p></div></div>
<p>Plusieurs personnes utilisent l’IA sur des tâches reliées. Le défi : garder des objectifs, des informations et des décisions clairs pour tout le monde.</p>
<p><strong>Exemple :</strong> une petite équipe prépare une proposition. Une personne utilise l’IA pour examiner des recherches approuvées. Une autre prépare le plan. Une troisième vérifie les engagements proposés. Elles décident de ce qu’elles peuvent partager et de qui valide la version finale.</p>
<p>H2S, HAI, A2A et H2H ont tous leur place. Chaque personne doit comprendre son rôle et les passages de relais. Dans nos formations, le niveau 4 concerne les membres d’une équipe au sein d’une organisation. Il ne promet pas de construire des systèmes d’IA pour toute l’organisation.</p>
<div class="acx-practice"><h3>Votre vérification en quatrième vitesse</h3><p>Chacun peut-il nommer la personne responsable, la source et la prochaine décision pour sa partie du travail ?</p></div><figure class="acx-drawing"><a class="acx-drawing-image" href="/images/acx/acx-4-original.png" target="_blank" rel="noopener noreferrer" aria-label="Agrandir le dessin dans un nouvel onglet"><img src="/images/acx/acx-4-original.png" width="1920" height="1080" loading="lazy" decoding="async" alt="Dessin original du niveau ACX 4, avec les connexions concernées mises en couleur."></a><figcaption>ACX 4 · Dessin original d’Estève Pannetier. Textes et périmètre d’origine conservés. <a href="/images/acx/acx-4-original.png" target="_blank" rel="noopener noreferrer">Agrandir ↗</a></figcaption></figure><a class="acx-back" href="#acx-overview">↑ Retour aux quatre niveaux</a></section>
<section id="acx-practice"><h2>À essayer : préparer une conversation difficile</h2>
<p>Choisissez un exemple sans enjeu sensible. Utilisez des détails inventés, pas des informations confidentielles sur un client ou un collègue.</p>
<ol><li><strong>Réfléchissez d’abord.</strong> Écrivez votre objectif en une phrase. Nommez une chose que vous ne savez pas.</li><li><strong>Demandez à l’IA.</strong> Décrivez la situation et demandez deux façons de l’expliquer.</li><li><strong>Vérifiez le brouillon.</strong> Cherchez les faits inventés, le contexte manquant et les promesses impossibles à tenir.</li><li><strong>Revenez à la personne.</strong> Utilisez le texte pour préparer une vraie conversation. Écoutez sa réponse.</li></ol>
<div class="acx-prompt"><h3>Un prompt à adapter</h3><p>Aide-moi à préparer une conversation sur [situation]. Mon objectif est [objectif]. Demande-moi les informations manquantes avant de rédiger. Propose deux façons de l’expliquer. N’invente pas de faits et ne prends pas d’engagements à ma place.</p></div>
<p>Notre <a href="/decode">Laboratoire de discours</a> propose une autre façon de relire votre message. Son modèle GreenBlueRed aide à repérer trois comportements de communication :</p>
<ul class="acx-colour-examples"><li class="acx-green"><strong>Vert · Créer du lien :</strong> « Je veux comprendre ce qui compte pour vous. »</li><li class="acx-blue"><strong>Bleu · Expliquer :</strong> « Voici ce qui a changé dans le plan. »</li><li class="acx-red"><strong>Rouge · Convenir d’une action :</strong> « Pouvons-nous choisir la prochaine étape ensemble ? »</li></ul>
<p>Ces couleurs décrivent des comportements de communication. Ce ne sont ni des niveaux ACX ni des étiquettes pour les personnes.</p></section>
<section id="acx-scan"><h2>Quelle est la place du Satellite Scan ?</h2>
<p>Le <a href="/scan">Satellite Scan</a> comprend un tableau de bord personnel de communication, des prompts de communication avancés et des supports pratiques, dont des vidéos de coaching et des fiches d’exercice. Les prompts vous aident à explorer vos résultats et à préparer de vraies conversations.</p>
<p>Le guide ACX permet de relier cette pratique à la prochaine étape de votre apprentissage :</p>
<ul><li><strong>Niveau 1 :</strong> utilisez un prompt pour réfléchir à une habitude de communication. Vérifiez si la réponse correspond à votre expérience.</li><li><strong>Niveau 2 :</strong> choisissez ce qui peut passer de votre réflexion au travail partagé, et ce qui doit rester privé.</li><li><strong>Niveau 3 :</strong> reprenez ces objectifs et ces limites quand vous explorez un assistant IA avec un accompagnement.</li><li><strong>Niveau 4 :</strong> discutez des rôles et des vérifications en équipe, sans supposer que chacun doit partager ses résultats personnels du Scan.</li></ul>
<p>C’est une façon d’utiliser les ressources au fil de l’apprentissage. Le Scan ne comprend ni un système d’agents installé ni le parcours accompagné de quatre jours. Les formations et le coaching se réservent séparément.</p><p><a class="acx-cta" href="/scan">Voir le Satellite Scan et ses options d’achat →</a></p></section>
<section id="acx-training"><aside class="acx-position"><h3>L’humain d’abord. L’IA avec discernement.</h3><p>Comprenez votre façon de travailler, explorez ce que l’IA peut vous apporter et gardez la main.</p><p>Le Scan vous aide à comprendre vos habitudes. Les ateliers vous aident à faire vos premiers pas. Le coaching et la formation pratique vous permettent de travailler sur vos propres tâches, en gardant votre voix et votre jugement.</p><p>Utilisez l’IA pour préparer les conversations difficiles, clarifier les malentendus et renforcer la confiance entre les personnes.</p><p>Partez d’un besoin réel. Essayez une petite tâche. Vérifiez les faits et le résultat. Gardez les outils qui vous aident et laissez les autres.</p></aside><h2>Quelle formation à l’IA vous convient ?</h2>
<p><strong>Atelier découverte :</strong> 3 h 30, pause comprise, pour 6 à 16 personnes. Découvrez les quatre niveaux et repartez avec des pistes pratiques aux niveaux 1 et 2 seulement.</p>
<p><strong>Parcours accompagné de quatre jours :</strong> un accompagnement pratique à temps partiel pour 1 à 5 personnes. Exercez-vous en profondeur aux niveaux 1 et 2, abordez le niveau 3 avec un guide et découvrez les principes du niveau 4.</p>
<p>Le but est de développer votre jugement, votre confiance et vos compétences de communication avec l’IA. Aucune formation ne peut rendre chaque réponse fiable à votre place.</p>
<p><a class="acx-cta" href="https://calendly.com/greenelephant/free-ai-literacy-discovery-call" target="_blank" rel="noopener noreferrer">Parlons de votre formation ↗</a></p></section>
<section id="acx-questions"><h2>Questions fréquentes</h2>
<details><summary>Faut-il savoir coder pour commencer ?</summary><p>Non. Commencez par des demandes claires et des vérifications attentives. Relier des outils ou configurer des agents peut demander une aide technique supplémentaire.</p></details>
<details><summary>Les niveaux ACX sont-ils une certification ou une norme ?</summary><p>Non. Ils constituent le cadre pédagogique d’Estève. Suivre une formation ne certifie pas une personne, une équipe ou un système à un niveau donné.</p></details>
<details><summary>Dois-je acheter le Satellite Scan pour lire ce guide ?</summary><p>Non. Ce guide et son exercice peuvent être utilisés seuls. Le Scan apporte des supports de réflexion personnels si vous choisissez de l’utiliser.</p></details></section>
<footer class="acx-source"><h2>À propos de ce guide</h2>
<p>Écrit par Estève Pannetier, coach en communication avec l’IA chez Green Elephant. Ce guide est une adaptation pratique de <a href="https://www.linkedin.com/pulse/four-levels-ai-integration-nobody-warned-you-est%C3%A8ve-pannetier-rptff/" target="_blank" rel="noopener noreferrer">The Four Levels of AI Integration Nobody Warned You About</a>, publié sur LinkedIn le 9 janvier 2026.</p>
<p>L’article d’origine utilise des schémas dessinés à la main et l’image des vitesses. Cette version conserve la progression, ajoute des exemples simples et reprend le périmètre actuel du niveau 4 : les membres d’une équipe. Le modèle est un outil pédagogique, pas un test validé des capacités.</p>
<p><a href="/connect#team">Rencontrer les coachs</a> · <a href="/resources#prompts">Explorer la bibliothèque de prompts</a> · <a href="/ai-policy">Lire notre politique d’utilisation de l’IA</a></p></footer>
</div></div>
`;

export const ACX_ARTICLE_FR_HTML = renderReadableAcx(ORIGINAL_ARTICLE_FR_HTML, 'fr');
