import { articleLinks, type SiteLanguage } from './site-language';

// Authored public policy copy. Owner/legal review gates live in the batch report.
export type PolicyPath = '/privacy' | '/ai-policy' | '/terms' | '/cookies';
type Section = { id: string; title: string; body: string };
type Policy = { title: string; description: string; summary: string[]; sections: Section[] };
const p = (...text: string[]) => text.map(t => `<p>${t}</p>`).join('');
const ul = (...text: string[]) => `<ul>${text.map(t => `<li>${t}</li>`).join('')}</ul>`;
const s = (id: string, title: string, body: string): Section => ({ id, title, body });
const email = '<a href="mailto:esteve@greenelephant.org">esteve@greenelephant.org</a>';
const external = (url: string, label: string) => `<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`;
const settings = '<a href="/portal/settings">Portal Settings (English)</a>';
const settingsFr = '<a href="/portal/settings" hreflang="en">Paramètres du portail (en anglais)</a>';
const arboraLink = '<a href="https://arbora.partners" target="_blank" rel="noopener noreferrer" data-testid="link-arbora">Arbora.partners</a>';
const research = 'https://www.arbora.partners/research';
const ga = 'https://policies.google.com/technologies/partner-sites';

export const POLICY_PAGES: Record<SiteLanguage, Record<PolicyPath, Policy>> = {
  en: {
    '/privacy': {
      title: 'Your privacy',
      description: 'What you share, how it is used, who receives it and how to exercise your rights.',
      summary: ['Share only what is needed for your enquiry or service. Avoid private information about other people.', 'Scan answers are sent to you by email and copied to Estève and Anu, the coaches supporting the service.', 'Optional website analytics need your permission. You can reject them and still use the site.', 'To ask for a copy, correction or deletion of your data, email Estève.'],
      sections: [
        s('controllers', '1. Who is responsible for your data?', p('The existing service notice names Estève Pannetier (Finland) for website administration and coaching, and Jonas Pannetier (France) for research and separate clinical psychology services.', `Contact ${email} about your data or the organisation responsible for your particular service. Separate clinical services require their own agreement and privacy information.`)),
        s('data', '2. What information is collected?', ul('<strong>Contact:</strong> your name, email, communication preferences and dated consent records.', '<strong>Services:</strong> enquiries, coaching selections, retreat waitlist motivation and preferences, newsletter subscriptions, Signals quiz answers, Check-my-FLOW results, Satellite Scan answers and results, and Prompting Playground requests and generated content.', '<strong>Payments:</strong> transaction and service records. Stripe handles card details; the website does not store your card number.', '<strong>Accounts and connections:</strong> sign-in profile information, account identifiers, session identifiers and access tokens for services you connect.', '<strong>Technical information:</strong> requests needed to deliver and protect the site. Optional Google Analytics receives limited public-page and link-click information only after acceptance. Google also receives technical information and cookie identifiers; this is not anonymous collection.') + p('The data needed depends on the feature you use. Do not include confidential client material or information about someone else without permission.')),
        s('bases', '3. Why may we use your data?', p('A legal basis is the reason the law allows personal data to be used. The existing notice describes these bases:') + ul('<strong>Consent:</strong> newsletter and waitlist updates, the Signals quiz, optional connected accounts and optional analytics. You can withdraw consent without changing the lawfulness of earlier use.', '<strong>Contract:</strong> information needed to arrange and deliver a purchased assessment, coaching, retreat, training or consulting service, including related confirmations.', '<strong>Legitimate interests:</strong> essential website operations and technical troubleshooting, balanced against your rights.', '<strong>Legal obligations:</strong> required tax and accounting records.') + p('Ask us which basis applies to a particular use. Giving a technical permission to connect an account does not itself settle every legal basis for using its data.')),
        s('purposes', '4. How is your information used?', ul('Respond to enquiries, arrange sessions and deliver the service you select.', 'Sign you in and manage your account.', 'Prepare communication reflections, Scan dashboards and practice materials.', 'Send results, purchase confirmations and support messages.', 'Send newsletters or retreat updates when you request them.', 'Process payments and keep required accounting records.', 'Maintain the website, investigate technical problems and protect access.', 'Export to your connected Notion workspace when you initiate an export; use the team workspace for relevant service records where that integration is enabled.')),
        s('recipients', '5. Who may receive it?', p('Providers support different parts of the service. Their involvement depends on the feature and enabled connection:') + ul('<strong>Estève and Anu:</strong> Scan results emails copy both coaches and include your submitted answers. Email copies are separate from your website account.', `<strong>Stripe:</strong> payments. ${external('https://stripe.com/privacy', 'Stripe privacy information')}.`, '<strong>Replit:</strong> website hosting. The actual publishing and database locations depend on the project settings; an EU location is not assumed.', '<strong>Resend:</strong> purchase, assessment-results and dashboard emails.', '<strong>Typeform:</strong> the Scan questionnaire and submitted answers sent to the website service.', '<strong>Cloudflare:</strong> website delivery and protection, including technical request information.', `<strong>Calendly:</strong> booking details when you schedule a session. ${external('https://calendly.com/privacy', 'Calendly privacy information')}.`, `<strong>Google:</strong> sign-in if chosen; optional Google Analytics 4 after acceptance. ${external(ga, 'How Google uses partner-site information')}.`, '<strong>LinkedIn:</strong> sign-in if chosen.', '<strong>Notion:</strong> team contact/service records and optional exports to a workspace you connect.', `<strong>Thesys:</strong> AI-assisted visualisations and content when enabled. The submitted prompt and supplied data are sent to Thesys. ${external('https://www.thesys.dev/privacy-policy', 'Thesys privacy information')}.`, '<strong>Fathom:</strong> optional meeting recording and AI notes only after explicit agreement before recording starts. You can decline recording and still attend the discovery call.') + p('The existing notice states that we do not sell or rent your personal data or share it for third-party marketing. Ask us for the recipients and provider arrangements for your service.')),
        s('connections', '6. Sign-in and connected workspaces', p('OAuth is a way to let a service connect without giving us your password for that service.') + ul('<strong>Google sign-in:</strong> name, email, profile picture and account identifier. The sign-in scopes are openid, email and profile; they do not grant access to your contacts, calendar or Drive.', '<strong>LinkedIn sign-in:</strong> name, email and profile identifier through openid, profile and email scopes. This sign-in does not grant access to connections, posts or company pages, or permission to post.', '<strong>Notion:</strong> workspace name and identifiers plus a connection token. Permissions depend on the pages and capabilities granted to the integration. A connection is not a guarantee that no reading is possible.') + p(`Where available, manage connections in ${settings}. The Notion disconnect action clears its token and workspace identifiers from the active account record. It does not erase data already exported to Notion or prove deletion from backups or provider systems. Contact us to check the scope of a disconnection or deletion.`)),
        s('transfers', '7. Processing outside Europe', p('Providers may process data outside the European Economic Area, including in the United States. Provider contracts, service settings and the destination determine which safeguards apply.', `Contact ${email} for the locations and transfer safeguards that apply to your information, and how to obtain a copy of those safeguards. Provider documentation alone does not confirm our account settings or agreements.`)),
        s('retention', '8. How long is information kept?', p('The existing notice lists the following periods. The team needs to confirm the service-specific schedule and how deletion is carried out:') + ul('<strong>Contact and marketing records:</strong> 24 months after the last interaction, unless consent is withdrawn sooner.', '<strong>Retreat waitlists:</strong> until the retreat cycle ends, plus 12 months.', '<strong>Assessment answers and results:</strong> ask us for the applicable period. This application does not provide automatic anonymisation.', '<strong>Connection tokens:</strong> while connected, subject to disconnection or account-deletion requests.', '<strong>Portal account records:</strong> until deletion is requested, subject to records that must be retained.', '<strong>Contracts and payments:</strong> the earlier notice states 6–10 years. The period depends on the record and applicable national accounting law; this is not a single EU-wide retention rule.', '<strong>Analytics:</strong> the browser preference and configured GA cookie expiry are 180 days. Google account-side retention is a separate setting.') + p('Website records, coach inboxes, exports, recordings, provider records and backups may need separate handling. Contact us for the period and deletion process for each.')),
        s('rights', '9. Your data protection rights', p('Under the GDPR, subject to its conditions and exceptions, you can:') + ul('Ask for access and a copy of your personal data.', 'Correct inaccurate or incomplete information.', 'Request erasure or restrict its use.', 'Receive eligible data in a machine-readable format (portability).', 'Object to use based on legitimate interests; object to direct marketing at any time.', 'Withdraw consent at any time, including analytics or newsletter consent.', 'Challenge a decision based solely on automated processing that has legal or similarly significant effects, where this protection applies.', 'Complain to a data protection authority or seek a court remedy.') + p(`Send requests to ${email}. We must respond without undue delay, normally within one month. Complex or numerous requests may take up to two extra months; we must explain the extension within the first month. We may need proportionate information to confirm your identity.`)),
        s('deletion', '10. Ask for deletion', p(`Email ${email} with the subject “Data deletion request” and tell us which service or records you mean. Account or connection controls, where available, can help you manage access; disconnecting a provider is not the same as deleting every copy.`, 'We will explain the action taken, any records that must remain for a legal reason and any applicable limits. The response period described above is not a promise that all website, provider, email and backup copies disappear within 30 days.')),
        s('security', '11. Protecting your information', p('The website uses account access controls and sessions. Its password-hashing code uses scrypt with a separate salt. Production sessions are configured to use secure, HTTP-only cookies; public production connections use HTTPS.', 'These measures reduce risk but do not guarantee complete security. Ask us about access, monitoring, provider agreements and safeguards for your service. Do not send passwords or sensitive material in a support email.')),
        s('ai', '12. AI and human judgement', p('AI can support content and dashboard preparation. A coach-prepared dashboard can include AI-assisted material. People remain responsible for the service and for deciding how to use their reflections.', 'The ACX teaching map is not a clinical diagnosis, certification or legal compliance assessment. Read the <a href="/ai-policy">AI policy</a> for the tools, limits and questions to ask.') + p(`Estève’s related communication and AI research is described at ${external(research, 'Arbora research')}. That link does not authorise transfer of your data to Arbora.`)),
        s('children', '13. Children', p('Services are intended for adults aged 18 or over. The existing notice states that we do not knowingly collect information from children under 16. If a child has submitted information, contact us promptly so we can investigate and address it.')),
        s('updates', '14. Changes to this notice', p('We may update this notice when practices or legal requirements change. Significant changes will be announced by email or a website notice. If consent is needed for a new use, we must ask separately; browsing the site does not give that consent.')),
        s('complaints', '15. Questions and complaints', p(`Contact ${email} about a concern. You may also complain to the authority where you live, work or believe a breach occurred. You do not have to contact us first.`) + ul(`${external('https://tietosuoja.fi/en/home', 'Finland: Office of the Data Protection Ombudsman')}.`, `${external('https://www.cnil.fr/en', 'France: CNIL')}.`)),
      ],
    },
    '/ai-policy': {
      title: 'How we use AI', description: 'Learn what AI can help with, what to check and how to raise a concern.',
      summary: ['AI literacy means knowing when to use AI, how to check its answers and when to stop.', 'AI can help prepare content and visualisations. A coach-prepared dashboard may include AI assistance.', 'AI can make mistakes. Keep your judgement and protect private information.', 'Coaching, interviews and retreats remain their existing services. AI training is included only when the booked offer says so.'],
      sections: [
        s('purpose', '1. People stay responsible', p('Conscious communication helps you clarify a goal, give useful context, ask questions and check whether an answer fits. These are useful skills for working with AI while keeping your own voice.', 'Our aim is to support human judgement and human connection. AI output is something to review, not a decision you must follow.')),
        s('uses', '2. Where AI can be involved', ul('<strong>Satellite Scan:</strong> coaches prepare your dashboard. The website also has an enabled-provider pathway for generating dashboard visualisations from a prompt and supplied data. “Coach-prepared” does not mean every step is manual or that AI only summarises.', '<strong>Prompts and resources:</strong> AI can help draft example requests and supporting material. When you use a prompt in your own AI tool, that provider’s terms and data settings apply.', '<strong>Communication visualisations and content:</strong> Thesys can generate visualisations and drafts when the relevant connection is enabled. Its current dashboard request uses a model identified as Anthropic Claude through Thesys.', '<strong>Website illustrations:</strong> some refreshed website scenes were generated or edited with AI. They illustrate possible practice settings and are not evidence of real clients, staff or training sessions.', '<strong>Meeting notes:</strong> optional Fathom recording and AI notes require explicit agreement before recording starts; declining recording does not prevent the discovery call.') + p('Tool availability depends on the service and its enabled settings. Ask which tools and data will be involved in your own service before sharing sensitive information.')),
        s('data', '3. Information sent to AI tools', p('For the website’s Thesys generation pathway, the request includes the prompt and any data supplied with it. That information is processed by Thesys and its model-provider arrangements.', 'Do not assume a consumer AI account is private or that a provider never uses inputs for training. Retention, training use, subprocessors and transfer safeguards depend on the applicable service agreement and settings. These need service-specific confirmation.', 'Use fictional or suitably anonymised practice examples where possible. Do not upload confidential client or colleague information without the authority to do so. See the <a href="/privacy">privacy notice</a> for recipients and rights.')),
        s('checks', '4. Checking outputs', p('AI may invent facts, omit context or reproduce bias. Check names, dates, calculations, links and tone before using an output. Consider how the person receiving it may understand it.', 'Ask the coach what was generated, what was checked and what remains uncertain. This notice does not promise that every output has been labelled or reviewed, or that all analysis is human-only.', 'Communication reflections and ACX levels are learning tools, not clinical diagnoses or suitability scores for hiring, credit or other decisions affecting someone’s rights.')),
        s('law', '5. AI literacy and the law', p('The EU AI Act is a reference for reviewing responsible use. Our ACX map and learning offers do not certify legal compliance. An AI system’s legal risk classification depends on its purpose and use; this page does not classify every application as minimal or limited risk.', `See the ${external('https://digital-strategy.ec.europa.eu/en/faqs/ai-literacy-questions-answers', 'European Commission’s AI literacy guidance')}. Learning a framework does not replace reviewing the systems used in your organisation.`, 'The teaching approach supports transparency, appropriate human oversight and data protection. It does not authorise manipulation, exploitation of vulnerabilities or automated decisions about people’s rights.')),
        s('choice', '6. Your choices and concerns', ul(`Ask ${email} which AI tools are involved and how they contribute to an output.`, 'Ask whether a human-only option is available before booking or submitting data. This is a request to discuss alternatives, not a guaranteed option for every service.', 'Question or correct an output and ask for a human explanation.', 'Exercise applicable access, objection, consent and automated-decision rights under the GDPR. These depend on the processing and legal conditions; they are not limited to what is technically convenient.', 'Complain to a relevant data protection authority. See the <a href="/privacy#rights">privacy rights section</a>.')),
        s('services', '7. Coaching, interviews and retreats', p('The existing coaching, interview and retreat services keep their agreed scope. Practising clear goals, listening and thoughtful feedback can support AI literacy, but this connection does not turn those services into new AI offers.', 'AI training and coaching are booked according to the specific offer. Do not assume AI training is included in a retreat, interview bundle or communication session.')),
        s('research', '8. Research and updates', p(`The ACX teaching map draws on Estève’s AI and communication research, including work described at ${external(research, 'Arbora research')}. Visit ${arboraLink} for more about that project. Green Elephant and Arbora are separate projects; this reference does not mean your service data is shared with Arbora.`, `We may update this notice as tools and practices change. For questions or concerns, contact ${email}.`)),
      ],
    },
    '/terms': {
      title: 'Terms of service', description: 'What you book, how payment and cancellation work, and what to expect.',
      summary: ['Check the offer and booking agreement for the exact service, price, tax, dates and inclusions.', 'Existing coaching, interview and retreat services keep their scope. AI training is not automatically included.', 'Cancellation terms differ by service. Mandatory consumer rights still apply.', 'These services support learning and development; individual results are not guaranteed.'],
      sections: [
        s('agreement', '1. The agreement and service provider', p('These terms describe use of GreenElephant.org and its services. Review them before booking. If you do not accept the proposed service terms, do not book that service.', `The existing notice names ${external('https://www.linkedin.com/in/estève-pannetier-3a883217', 'Estève Pannetier')} (Finland), ${external('https://www.linkedin.com/in/jonas-pannetier-6a7728134', 'Jonas Pannetier')} (France) and ${external('https://www.linkedin.com/in/anutimmerbacka', 'Anu Timmerbacka')} (Finland) as operators. Check your booking agreement for the legal seller responsible for your service.`, `For questions about the agreement or seller, contact ${email}. Reading the site is not consent to optional analytics or recording.`)),
        s('offers', '2. Services and prices', p('AI literacy training helps beginners practise with AI while retaining their judgement. The selected offer sets its format, scope and fee. Conscious communication can support that learning; it does not mean existing services include AI training.') + ul('<strong>Coaching:</strong> single session €295; Coaching Journey, about six months, €2,980; team workshop €1,200 for up to 10 people; interview coaching €845 for a three-session bundle.', '<strong>Retreats:</strong> Equinoxe in Provence, France or Levi, Finland, €2,890; five-day experiences with personal microhabit playbooks and 90-day integration support.', '<strong>Consulting:</strong> Executive Leadership Intensive €18,000; TEAL Organization Transformation €28,000; Innovation Team Design Sprint €12,000.', '<strong>Satellite Scan:</strong> €99.95 for the assessment, coach-prepared dashboard, prompts and practice materials. Training and coaching are booked separately.') + p('These retained service descriptions do not confirm availability or a booking. Review the current offer, included items, applicable VAT and final total before payment. Do not assume all services have the same tax treatment.')),
        s('payment', '3. Booking and payment', p('Prices are in euros (EUR). Changes are announced for future bookings and do not automatically change an agreed booking price. Stripe handles online payments; authorisation applies to the selected service and displayed amount.') + ul('Coaching packages: full payment at booking.', 'Retreats: payment on registration; food, accommodation and travel are excluded.', 'Consulting: 50% deposit, with the balance due before project completion.') + p('Check the service agreement for dates, tax, inclusions and any different agreed payment schedule.')),
        s('cancellation', '4. Cancellation and refunds', p('The existing service notice states these cancellation terms:') + ul('<strong>Coaching:</strong> at least 48 hours’ notice for a full refund. With less notice, no refund, but one rescheduling may be offered. No-shows are non-refundable and non-transferable.', '<strong>Retreats:</strong> more than 90 days before: 90% refund; 60–90 days before: 50%; less than 60 days before: no refund, but you may transfer your place. If organisers cancel, a full refund is offered.', '<strong>Consulting:</strong> the individual agreement sets cancellation terms. Deposits are generally non-refundable once work has begun.', '<strong>Scan:</strong> the current offer says you can request a full refund within 14 days.') + p('These commercial terms do not remove mandatory consumer rights. For distance contracts, withdrawal rights and exceptions depend on the type of service and when performance begins. Any request to start early and any required acknowledgement of losing a withdrawal right must be handled separately; browsing or paying is not a blanket waiver.', `Contact ${email} about cancellation and the terms for your booking. See ${external('https://www.kkv.fi/en/consumer-affairs/', 'Finland’s consumer authority')} for consumer guidance.`)),
        s('delivery', '5. Delivery and participation', p('Sessions are scheduled through Calendly or by mutual agreement. We make reasonable efforts to accommodate preferences.') + ul('Give accurate intake and assessment information.', 'Attend on time and take part in the agreed learning or coaching process.', 'Communicate respectfully with coaches and participants.', 'Check your offer for delivery timing, language and what is included.') + p('Optional discovery-call recording with Fathom requires explicit agreement before it starts. You can attend without recording.')),
        s('limits', '6. Limits and responsibility', p('Communication coaching and training are educational and developmental. They do not replace medical, psychological or therapeutic treatment. Separate clinical services, if arranged, need their own provider information and agreement.', 'Results vary with circumstances, engagement and practice. We do not guarantee career advancement, relationship improvements or specific outcomes.', 'The existing terms limit indirect, incidental and consequential loss and cap liability at the amount paid for the relevant service, only to the extent the law allows. Nothing here excludes liability or consumer remedies that cannot lawfully be excluded. These limits require review for the applicable service and customer.')),
        s('materials', '7. Materials and recordings', p('The existing notice attributes the communication framework, course material, prompts, infographics and methods to Estève Pannetier, Jonas Pannetier and Anu Timmerbacka. Third-party material keeps its own rights and licence terms.', '<strong>Personal use:</strong> you may download and use the resources for personal, non-commercial purposes. Commercial reproduction, distribution or adaptations require written permission unless a specific licence says otherwise.', '<strong>Recordings:</strong> any agreed session recording is for your personal review and may not be shared publicly or commercially. A booking does not itself give permission to record other participants.')),
        s('confidentiality', '8. Confidentiality', p('Coaching conversations, assessments and personal information are handled as confidential. Service delivery can involve the coaches and providers described in the <a href="/privacy">privacy notice</a>, including Scan email copies to Estève and Anu.') + ul('Disclosure may be made with your explicit consent.', 'Disclosure may be required by law or legal process.', 'Safety concerns involving imminent harm may require appropriate action within the law.', 'Research or testimonial use requires permission and appropriate anonymisation; we do not promise that removing a name makes every record anonymous.')),
        s('conduct', '9. Respectful participation', p('Harassment, discrimination, hate speech, disruption, breaches of others’ confidentiality and unlawful use are not acceptable.', 'The existing terms allow service termination and denial of refunds for conduct violations, subject to the contract and mandatory legal rights. This does not create an automatic exemption from consumer protections.')),
        s('law', '10. Law and courts', p('The existing terms choose Finnish law and Helsinki courts, with mediation if mutually agreed. Mandatory consumer protections and jurisdiction rights still apply; this clause does not force every consumer to bring a claim only in Helsinki.', 'For services delivered in France, applicable French protections must also be considered. The seller, customer location and service determine which rules apply.')),
        s('disputes', '11. Resolving a concern', p(`Contact ${email} to explain the issue. We aim to resolve concerns through discussion. Mediation can be agreed, but it is not a condition that removes a right to seek help from a consumer authority or court.`)),
        s('updates', '12. Changes to these terms', p('Updates may reflect service or legal changes. Significant changes will be announced by email or a website notice. Changes to an existing booking depend on the agreement and applicable law; continued browsing does not waive rights or automatically accept a changed paid contract.')),
      ],
    },
    '/cookies': {
      title: 'Cookies and your choices', description: 'Keep essential features working. Choose whether to allow optional website analytics.',
      summary: ['Essential sign-in cookies help the service work. Blocking them may prevent account access.', 'Optional Google Analytics loads only after acceptance and only when enabled on the production site.', 'Rejecting analytics leaves the site available. You can change your choice at any time.', 'Withdrawal stops future website tracking; it does not erase information already received by Google.'],
      sections: [
        s('meaning', '1. What are cookies?', p('Cookies are small files a website stores on your device. They can keep you signed in or remember a preference. Local storage is another way a browser can save a choice; it is not a cookie.')),
        s('essential', '2. Essential cookies', p('The website session cookie is <code>connect.sid</code>. It keeps account sessions working and is configured to last up to seven days. It is marked HTTP-only, SameSite=Lax and secure in production.', 'You can block it in your browser, but features such as staying signed in may stop working. Essential functionality does not depend on accepting analytics.')),
        s('analytics', '3. Optional Google Analytics', p('When enabled on the production site and accepted, Google Analytics 4 measures visits and selected enquiry/Scan checkout-link clicks on the homepage, Scan and five AI coaching pages. A click is not proof of a booking or purchase.') + ul('No Google Analytics tag from this website loads before acceptance or after an initial rejection.', 'The website sends the allowed public page path, language, broad referral category and selected click labels. Google also processes technical request/device information and cookie identifiers; this is not anonymous measurement.', 'This measurement excludes names, emails, purchase identifiers, questionnaire answers, scores, full referrer URLs and URL query strings.', 'Private, account, checkout, results and MyFive pages are excluded. Google advertising signals and ad personalisation are disabled.', 'GA cookies named <code>_ga</code> and <code>_ga_*</code> are configured to expire after 180 days without renewal.', 'Your Accept/Reject choice is stored in local storage as <code>ge.analytics-consent.v1</code> for 180 days. If storage is blocked, the choice may last only for the visit.', 'Withdrawal stops future tracking, clears the site’s accessible GA cookies and reloads where necessary. It does not erase historical provider data.') + p(`See ${external(ga, 'Google’s partner-site explanation')} and our <a href="/privacy">privacy notice</a>. Google account-side retention, contracts and transfer arrangements are separate from browser expiry.`) + '<button type="button" class="policy-button" data-cookie-preferences>Change my cookie choice</button>'),
        s('third-parties', '4. Other services and cookies', p('The website’s analytics code does not enable advertising or social media tracking cookies. Other services have their own behaviour and notices when you use them.') + ul(`${external('https://stripe.com/privacy', 'Stripe')}: payment and fraud-prevention technologies.`, `${external('https://calendly.com/privacy', 'Calendly')}: booking platform cookies.`, `${external('https://www.typeform.com/privacy/', 'Typeform')}: questionnaire technologies.`, `${external('https://policies.google.com/privacy', 'Google / YouTube')}: sign-in or embedded video technologies when used.`, `${external('https://www.cloudflare.com/privacypolicy/', 'Cloudflare')}: delivery and security technologies where applied.`) + p('The live cookie inventory and the loading of third-party embeds need their own verification. Rejecting this site’s analytics does not describe every cookie on a provider’s separate website.')),
        s('manage', '5. Manage cookies in your browser', p('Browser settings let you view or delete cookies, block third-party cookies, block sites or clear cookies on closing. Private browsing usually clears its session data when all private windows are closed; it does not make you anonymous.') + ul(external('https://support.google.com/chrome/answer/95647', 'Google Chrome'), external('https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop', 'Mozilla Firefox'), external('https://support.apple.com/guide/safari/manage-cookies-sfri11471/mac', 'Safari'), external('https://support.microsoft.com/en-us/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09', 'Microsoft Edge')) + p('Deleting cookies and local storage may remove your saved choice. You can use “Cookie choices” on the site to make a new choice.')),
        s('rights', '6. Your rights', p('You can refuse non-essential analytics, withdraw consent and ask about data collected. Deleting browser cookies does not by itself delete data already held by a provider.', `For applicable GDPR access, deletion, objection and complaint rights, read the <a href="/privacy#rights">privacy rights section</a> or email ${email}.`)),
        s('updates', '7. Changes', p('We may update this notice when the website’s cookie use changes. If a new use needs consent, it must be requested separately. The date below refers to this notice, not verification of every live provider setting.')),
      ],
    },
  },
  fr: {
    '/privacy': {
      title: 'Vos données personnelles', description: 'Ce que vous partagez, son utilisation, ses destinataires et vos droits.',
      summary: ['Partagez seulement ce qui est utile à votre demande ou au service. Évitez les informations privées sur d’autres personnes.', 'Vos réponses au Scan vous sont envoyées par courriel, avec copie à Estève et Anu, les coachs qui accompagnent le service.', 'La mesure facultative des visites nécessite votre accord. Vous pouvez la refuser et utiliser le site.', 'Pour demander une copie, une correction ou la suppression de vos données, écrivez à Estève.'],
      sections: [
        s('controllers', '1. Qui est responsable de vos données ?', p('La notice existante désigne Estève Pannetier (Finlande) pour le site et le coaching, et Jonas Pannetier (France) pour la recherche et les services distincts de psychologie clinique.', `Contactez ${email} pour connaître l’organisme responsable de votre service. Les services cliniques distincts nécessitent leur propre contrat et leur propre information sur les données.`)),
        s('data', '2. Quelles informations sont recueillies ?', ul('<strong>Contact :</strong> nom, adresse électronique, préférences de communication et preuves datées de consentement.', '<strong>Services :</strong> demandes, choix de coaching, motivation et préférences pour les listes d’attente des retraites, abonnement à la lettre d’information, réponses au quiz Signals, résultats Check-my-FLOW, réponses et résultats du Satellite Scan, demandes et contenus du Prompting Playground.', '<strong>Paiements :</strong> transactions et dossiers de service. Stripe traite les coordonnées de carte ; le site ne conserve pas votre numéro de carte.', '<strong>Comptes et connexions :</strong> informations de profil, identifiants de compte et de session, et jetons d’accès aux services que vous connectez.', '<strong>Informations techniques :</strong> requêtes nécessaires au fonctionnement et à la protection du site. Google Analytics reçoit des informations limitées sur les pages publiques et les clics seulement après acceptation. Google reçoit aussi des informations techniques et des identifiants de cookies ; cette collecte n’est pas anonyme.') + p('Les données nécessaires dépendent de la fonction utilisée. Ne fournissez pas d’informations confidentielles sur un client ou une autre personne sans autorisation.')),
        s('bases', '3. Pourquoi pouvons-nous utiliser vos données ?', p('Une base juridique est la raison qui autorise l’utilisation de données personnelles. La notice existante décrit les bases suivantes :') + ul('<strong>Consentement :</strong> lettre d’information, mises à jour des listes d’attente, quiz Signals, connexions facultatives et mesure des visites. Vous pouvez retirer votre accord sans remettre en cause l’utilisation antérieure licite.', '<strong>Contrat :</strong> informations nécessaires à l’organisation et à la fourniture du bilan, coaching, retraite, formation ou conseil acheté, y compris les confirmations liées au service.', '<strong>Intérêts légitimes :</strong> fonctionnement essentiel du site et résolution de problèmes techniques, en tenant compte de vos droits.', '<strong>Obligations légales :</strong> documents fiscaux et comptables requis.') + p('Demandez-nous quelle base s’applique à une utilisation précise. Une autorisation technique de connexion ne règle pas à elle seule toutes les bases juridiques du traitement.')),
        s('purposes', '4. À quoi servent vos informations ?', ul('Répondre aux demandes, organiser les séances et fournir le service choisi.', 'Vous connecter et gérer votre compte.', 'Préparer les réflexions sur la communication, les tableaux de bord Scan et les supports de pratique.', 'Envoyer les résultats, confirmations d’achat et messages d’assistance.', 'Envoyer la lettre d’information ou des nouvelles des retraites si vous les demandez.', 'Traiter les paiements et conserver les documents comptables requis.', 'Entretenir le site, résoudre les problèmes techniques et protéger les accès.', 'Exporter vers votre espace Notion lorsque vous lancez un export ; conserver les dossiers de service utiles dans l’espace de l’équipe lorsque cette intégration est activée.')),
        s('recipients', '5. Qui peut recevoir vos données ?', p('Les prestataires interviennent selon la fonction utilisée et les connexions activées :') + ul('<strong>Estève et Anu :</strong> les courriels de résultats Scan incluent vos réponses et sont copiés aux deux coachs. Ces copies sont distinctes de votre compte sur le site.', `<strong>Stripe :</strong> paiements. ${external('https://stripe.com/privacy', 'Informations de confidentialité de Stripe')}.`, '<strong>Replit :</strong> hébergement du site. La localisation du site publié et de la base de données dépend des réglages du projet ; une localisation dans l’UE n’est pas présumée.', '<strong>Resend :</strong> courriels d’achat, de résultats et de tableau de bord.', '<strong>Typeform :</strong> questionnaire Scan et transmission des réponses au service du site.', '<strong>Cloudflare :</strong> diffusion et protection du site, avec des informations techniques sur les requêtes.', `<strong>Calendly :</strong> informations de réservation. ${external('https://calendly.com/privacy', 'Informations de confidentialité de Calendly')}.`, `<strong>Google :</strong> connexion si choisie et Google Analytics 4 facultatif après accord. ${external(ga, 'Utilisation des informations des sites partenaires')}.`, '<strong>LinkedIn :</strong> connexion si choisie.', '<strong>Notion :</strong> dossiers de contact et de service de l’équipe, et exports facultatifs vers un espace connecté.', `<strong>Thesys :</strong> visualisations et contenus assistés par IA lorsque la connexion est activée. La consigne et les données fournies sont envoyées à Thesys. ${external('https://www.thesys.dev/privacy-policy', 'Informations de confidentialité de Thesys')}.`, '<strong>Fathom :</strong> enregistrement facultatif et notes par IA, seulement après accord explicite avant le début de l’enregistrement. Vous pouvez refuser et participer à l’appel découverte.') + p('La notice existante indique que nous ne vendons ni ne louons vos données et ne les partageons pas pour le marketing de tiers. Demandez-nous les destinataires et les accords applicables à votre service.')),
        s('connections', '6. Connexion et espaces liés', p('OAuth permet de connecter un service sans nous donner votre mot de passe de ce service.') + ul('<strong>Connexion Google :</strong> nom, courriel, photo de profil et identifiant. Les autorisations openid, email et profile ne donnent pas accès aux contacts, au calendrier ou à Drive.', '<strong>Connexion LinkedIn :</strong> nom, courriel et identifiant via openid, profile et email. Cette connexion ne donne pas accès aux relations, publications ou pages d’entreprise et ne permet pas de publier en votre nom.', '<strong>Notion :</strong> nom et identifiants de l’espace, avec un jeton de connexion. Les droits dépendent des pages et capacités accordées à l’intégration. Une connexion ne garantit pas qu’aucune lecture n’est possible.') + p(`Gérez les connexions disponibles dans les ${settingsFr}. La déconnexion Notion efface son jeton et les identifiants de l’espace dans le dossier de compte actif. Elle ne supprime pas les exports déjà réalisés et ne prouve pas l’effacement des sauvegardes ou des systèmes du prestataire. Demandez-nous la portée exacte de la déconnexion ou de la suppression.`)),
        s('transfers', '7. Traitement hors d’Europe', p('Les prestataires peuvent traiter des données hors de l’Espace économique européen, notamment aux États-Unis. Les contrats, réglages et destinations déterminent les garanties applicables.', `Contactez ${email} pour connaître les localisations et garanties de transfert applicables, et obtenir une copie de ces garanties. La documentation d’un prestataire ne confirme pas nos propres réglages ou contrats.`)),
        s('retention', '8. Durée de conservation', p('La notice existante indique les durées suivantes. L’équipe doit confirmer le calendrier propre au service et sa mise en œuvre :') + ul('<strong>Contacts et marketing :</strong> 24 mois après la dernière interaction, sauf retrait préalable du consentement.', '<strong>Listes d’attente des retraites :</strong> jusqu’à la fin du cycle de retraite, puis 12 mois.', '<strong>Réponses et résultats des bilans :</strong> demandez la durée applicable. Cette application ne fournit pas d’anonymisation automatique.', '<strong>Jetons de connexion :</strong> tant que le service est connecté, sous réserve de déconnexion ou de demande de suppression du compte.', '<strong>Dossiers du portail :</strong> jusqu’à la demande de suppression, sous réserve des documents à conserver.', '<strong>Contrats et paiements :</strong> l’ancienne notice indique 6 à 10 ans. La durée dépend du document et du droit comptable national ; ce n’est pas une règle unique de l’UE.', '<strong>Mesure des visites :</strong> le choix dans le navigateur et l’expiration configurée des cookies GA sont de 180 jours. La conservation dans le compte Google est distincte.') + p('Dossiers du site, courriels des coachs, exports, enregistrements, dossiers des prestataires et sauvegardes peuvent nécessiter des actions séparées. Demandez-nous leur durée et leur procédure de suppression.')),
        s('rights', '9. Vos droits sur les données', p('Selon les conditions et exceptions du RGPD, vous pouvez :') + ul('Demander l’accès à vos données et une copie.', 'Corriger les informations inexactes ou incomplètes.', 'Demander l’effacement ou limiter l’utilisation.', 'Recevoir les données éligibles dans un format lisible par machine : la portabilité.', 'Vous opposer à un traitement fondé sur les intérêts légitimes ; refuser la prospection à tout moment.', 'Retirer votre consentement, notamment pour la mesure des visites ou la lettre d’information.', 'Contester une décision uniquement automatisée produisant des effets juridiques ou similaires importants, lorsque cette protection s’applique.', 'Déposer une plainte auprès d’une autorité ou saisir un tribunal.') + p(`Écrivez à ${email}. Nous devons répondre sans retard injustifié, normalement sous un mois. Les demandes nombreuses ou complexes peuvent nécessiter deux mois supplémentaires ; la prolongation doit être expliquée dans le premier mois. Une vérification proportionnée de votre identité peut être nécessaire.`)),
        s('deletion', '10. Demander la suppression', p(`Écrivez à ${email} avec l’objet « Demande de suppression des données » et précisez le service ou les dossiers concernés. Les contrôles du compte et des connexions, lorsqu’ils existent, aident à gérer l’accès ; déconnecter un prestataire ne supprime pas toutes les copies.`, 'Nous expliquerons les mesures prises, les documents à conserver pour une raison légale et les limites applicables. Le délai de réponse ci-dessus ne promet pas l’effacement de toutes les copies du site, des prestataires, des courriels et des sauvegardes sous 30 jours.')),
        s('security', '11. Protection des informations', p('Le site utilise des contrôles d’accès et des sessions. Le code de hachage des mots de passe utilise scrypt avec un sel distinct. Les cookies de session sont configurés comme sécurisés et HTTP-only en production ; les connexions publiques de production utilisent HTTPS.', 'Ces mesures réduisent le risque sans garantir une sécurité absolue. Demandez-nous les contrôles, la surveillance, les accords et les garanties applicables. N’envoyez pas de mots de passe ou de données sensibles dans un courriel d’assistance.')),
        s('ai', '12. IA et jugement humain', p('L’IA peut aider à préparer du contenu et des tableaux de bord. Un tableau de bord préparé par un coach peut inclure cette aide. Les personnes restent responsables du service et de l’utilisation de leurs réflexions.', 'La carte pédagogique ACX n’est ni un diagnostic clinique, ni une certification, ni une évaluation de conformité juridique. Consultez la <a href="/ai-policy">politique IA</a> pour les outils, limites et questions à poser.', `Les recherches liées d’Estève sont présentées sur ${external(research, 'Arbora recherche')}. Ce lien n’autorise pas le transfert de vos données à Arbora.`)),
        s('children', '13. Enfants', p('Les services s’adressent aux adultes de 18 ans ou plus. La notice existante indique que nous ne recueillons pas sciemment de données d’enfants de moins de 16 ans. Si un enfant a transmis des informations, contactez-nous rapidement pour examiner et traiter la situation.')),
        s('updates', '14. Modifications de la notice', p('La notice peut évoluer avec les pratiques ou la loi. Les changements importants seront annoncés par courriel ou sur le site. Si un nouvel usage nécessite votre consentement, il doit être demandé séparément ; naviguer ne vaut pas consentement.')),
        s('complaints', '15. Questions et plaintes', p(`Contactez ${email} en cas de préoccupation. Vous pouvez aussi saisir l’autorité du lieu où vous vivez, travaillez ou pensez qu’une violation a eu lieu. Vous n’avez pas à nous contacter d’abord.`) + ul(external('https://tietosuoja.fi/en/home', 'Finlande : autorité de protection des données'), external('https://www.cnil.fr/fr', 'France : CNIL'))),
      ],
    },
    '/ai-policy': {
      title: 'Comment nous utilisons l’IA', description: 'Ce que l’IA peut aider à faire, les vérifications utiles et les questions à poser.',
      summary: ['Comprendre l’IA, c’est savoir quand l’utiliser, comment vérifier ses réponses et quand s’arrêter.', 'L’IA peut aider à préparer des contenus et des visualisations. Un tableau de bord préparé par un coach peut intégrer cette aide.', 'L’IA peut se tromper. Gardez votre jugement et protégez les informations privées.', 'Coaching, entretiens et retraites conservent leur contenu. La formation IA est incluse seulement si l’offre réservée le précise.'],
      sections: [
        s('purpose', '1. Les personnes restent responsables', p('La communication consciente aide à clarifier un objectif, donner un contexte utile, poser des questions et vérifier si une réponse convient. Ces compétences servent aussi à travailler avec l’IA en gardant votre propre voix.', 'Notre objectif est de soutenir le jugement humain et les relations. Une réponse d’IA est à examiner ; ce n’est pas une décision à suivre automatiquement.')),
        s('uses', '2. Où l’IA peut intervenir', ul('<strong>Satellite Scan :</strong> les coachs préparent votre tableau de bord. Le site comprend aussi une fonction de génération de visualisations à partir d’une consigne et de données, lorsque le prestataire est activé. « Préparé par un coach » ne signifie pas que chaque étape est manuelle ou que l’IA sert seulement à résumer.', '<strong>Consignes et ressources :</strong> l’IA peut aider à rédiger des exemples de demandes et des supports. Si vous utilisez une consigne dans votre propre outil, les conditions et réglages de ce prestataire s’appliquent.', '<strong>Visualisations et contenus :</strong> Thesys peut générer des visualisations et des brouillons lorsque la connexion est activée. La requête actuelle de tableau de bord utilise un modèle identifié comme Anthropic Claude via Thesys.', '<strong>Illustrations du site :</strong> certaines scènes du site rénové ont été générées ou modifiées avec l’IA. Elles illustrent des situations possibles ; elles ne prouvent pas la présence de vrais clients, collaborateurs ou séances de formation.', '<strong>Notes de réunion :</strong> l’enregistrement Fathom et les notes par IA sont facultatifs et nécessitent un accord explicite préalable. Vous pouvez participer à l’appel découverte sans enregistrement.') + p('La disponibilité dépend du service et des réglages activés. Demandez quels outils et données seront concernés avant de partager des informations sensibles.')),
        s('data', '3. Informations envoyées aux outils', p('Pour la fonction Thesys du site, la requête contient la consigne et les données fournies avec elle. Thesys les traite selon ses accords avec les fournisseurs de modèles.', 'Ne supposez pas qu’un compte grand public est privé ou que les entrées ne servent jamais à entraîner un modèle. Conservation, entraînement, sous-traitants et transferts dépendent du contrat et des réglages. Une confirmation propre au service est nécessaire.', 'Utilisez si possible des exemples fictifs ou correctement anonymisés. Ne transmettez pas d’informations confidentielles de clients ou collègues sans autorisation. Consultez la <a href="/privacy">notice sur les données</a>.')),
        s('checks', '4. Vérifier les réponses', p('L’IA peut inventer des faits, omettre le contexte ou reproduire des biais. Vérifiez noms, dates, calculs, liens et ton. Réfléchissez à la manière dont la personne destinataire comprendra le message.', 'Demandez au coach ce qui a été généré, vérifié et reste incertain. Cette notice ne promet pas que tous les contenus sont étiquetés ou revus, ni que toute l’analyse est exclusivement humaine.', 'Les réflexions sur la communication et les niveaux ACX sont pédagogiques. Ce ne sont pas des diagnostics ou des scores de sélection pour l’emploi, le crédit ou d’autres décisions affectant les droits.')),
        s('law', '5. Comprendre l’IA et le droit', p('Le règlement européen sur l’IA est une référence pour examiner les usages responsables. Notre carte ACX et nos formations ne certifient pas la conformité juridique. La catégorie de risque dépend de la finalité et de l’usage ; cette page ne classe pas toutes les applications à risque minimal ou limité.', `Consultez les ${external('https://digital-strategy.ec.europa.eu/en/faqs/ai-literacy-questions-answers', 'explications de la Commission européenne sur la maîtrise de l’IA')}. Apprendre un cadre ne remplace pas l’examen des systèmes de votre organisation.`, 'L’approche pédagogique soutient la transparence, le contrôle humain adapté et la protection des données. Elle n’autorise ni manipulation, ni exploitation de vulnérabilités, ni décisions automatisées sur les droits des personnes.')),
        s('choice', '6. Vos choix et préoccupations', ul(`Demandez à ${email} quels outils interviennent et comment ils contribuent aux résultats.`, 'Demandez avant la réservation ou l’envoi de données si une option sans IA existe. Il s’agit d’une discussion sur les alternatives, pas d’une option garantie pour chaque service.', 'Questionnez ou corrigez une réponse et demandez une explication humaine.', 'Exercez les droits applicables du RGPD : accès, opposition, retrait du consentement et protection face aux décisions automatisées. Ils dépendent du traitement et de la loi, pas seulement de la facilité technique.', 'Déposez une plainte auprès de l’autorité compétente. Consultez la <a href="/privacy#rights">section sur vos droits</a>.')),
        s('services', '7. Coaching, entretiens et retraites', p('Les services actuels conservent le contenu convenu. Clarifier ses objectifs, écouter et donner un retour réfléchi peut aider à comprendre l’IA. Ce lien ne transforme pas ces services en nouvelles offres IA.', 'La formation IA et le coaching se réservent selon l’offre précise. Ne supposez pas qu’une retraite, un forfait d’entretien ou une séance de communication inclut une formation IA.')),
        s('research', '8. Recherche et mises à jour', p(`La carte ACX s’appuie sur les recherches d’Estève en IA et communication, notamment les travaux présentés sur ${external(research, 'Arbora recherche')}. Consultez ${arboraLink} pour ce projet. Green Elephant et Arbora restent deux projets distincts ; cette référence ne signifie pas que vos données sont partagées avec Arbora.`, `Cette notice peut évoluer avec les outils et les pratiques. Pour toute question, contactez ${email}.`)),
      ],
    },
    '/terms': {
      title: 'Conditions de service', description: 'Ce que vous réservez, le paiement, l’annulation et les attentes.',
      summary: ['Vérifiez l’offre et le contrat pour le service exact, le prix, les taxes, les dates et les éléments inclus.', 'Coaching, entretiens et retraites gardent leur contenu. La formation IA n’est pas automatiquement incluse.', 'Les conditions d’annulation varient selon le service. Les droits impératifs des consommateurs restent applicables.', 'Ces services soutiennent l’apprentissage et le développement ; les résultats individuels ne sont pas garantis.'],
      sections: [
        s('agreement', '1. Contrat et prestataire', p('Ces conditions décrivent l’utilisation de GreenElephant.org et ses services. Lisez-les avant de réserver. Si vous n’acceptez pas les conditions proposées pour le service, ne le réservez pas.', `La notice existante nomme ${external('https://www.linkedin.com/in/estève-pannetier-3a883217', 'Estève Pannetier')} (Finlande), ${external('https://www.linkedin.com/in/jonas-pannetier-6a7728134', 'Jonas Pannetier')} (France) et ${external('https://www.linkedin.com/in/anutimmerbacka', 'Anu Timmerbacka')} (Finlande) comme opérateurs. Vérifiez dans le contrat l’identité du vendeur légal responsable du service.`, `Contactez ${email} pour toute question sur le contrat ou le vendeur. Lire le site ne vaut pas consentement à la mesure facultative des visites ou à un enregistrement.`)),
        s('offers', '2. Services et prix', p('La formation IA aide les débutants à pratiquer en gardant leur jugement. L’offre choisie précise le format, le contenu et le tarif. La communication consciente peut soutenir cet apprentissage ; cela ne signifie pas que tous les services incluent une formation IA.') + ul('<strong>Coaching :</strong> séance individuelle 295 € ; parcours d’environ six mois 2 980 € ; atelier d’équipe 1 200 € jusqu’à 10 personnes ; préparation aux entretiens 845 € pour trois séances.', '<strong>Retraites :</strong> Equinoxe en Provence ou à Levi, en Finlande, 2 890 € ; cinq jours avec un guide personnel de microhabitudes et un soutien d’intégration de 90 jours.', '<strong>Conseil :</strong> Executive Leadership Intensive 18 000 € ; TEAL Organization Transformation 28 000 € ; Innovation Team Design Sprint 12 000 €.', '<strong>Satellite Scan :</strong> 99,95 € pour le bilan, le tableau de bord préparé par un coach, les consignes et les supports de pratique. Formation et coaching réservés séparément.') + p('Ces descriptions conservées ne confirment ni disponibilité ni réservation. Vérifiez l’offre actuelle, les éléments inclus, la TVA applicable et le total avant de payer. Ne supposez pas que tous les services ont le même traitement fiscal.')),
        s('payment', '3. Réservation et paiement', p('Les prix sont en euros. Les modifications annoncées pour les réservations futures ne changent pas automatiquement un prix convenu. Stripe traite les paiements en ligne ; l’autorisation porte sur le service et le montant affichés.') + ul('Forfaits de coaching : paiement intégral à la réservation.', 'Retraites : paiement à l’inscription ; repas, hébergement et voyage exclus.', 'Conseil : acompte de 50 %, solde avant la fin du projet.') + p('Le contrat précise les dates, taxes, inclusions et tout échéancier différent convenu.')),
        s('cancellation', '4. Annulation et remboursement', p('La notice existante indique :') + ul('<strong>Coaching :</strong> remboursement intégral avec au moins 48 heures de préavis. Avec moins de préavis, aucun remboursement, mais un report peut être proposé une fois. Absence sans préavis : ni remboursement ni transfert.', '<strong>Retraites :</strong> plus de 90 jours avant : 90 % remboursés ; de 60 à 90 jours : 50 % ; moins de 60 jours : aucun remboursement, mais transfert de place possible. Si les organisateurs annulent, remboursement intégral proposé.', '<strong>Conseil :</strong> le contrat individuel fixe les conditions. Les acomptes ne sont généralement pas remboursables une fois le travail commencé.', '<strong>Scan :</strong> l’offre actuelle prévoit une demande de remboursement intégral sous 14 jours.') + p('Ces conditions commerciales ne suppriment pas les droits impératifs des consommateurs. Pour un contrat à distance, rétractation et exceptions dépendent du type de service et du début de son exécution. Une demande d’exécution anticipée et toute reconnaissance requise de perte du droit doivent être recueillies séparément ; lire ou payer ne vaut pas renonciation générale.', `Contactez ${email} pour votre réservation. Consultez ${external('https://www.kkv.fi/en/consumer-affairs/', 'l’autorité finlandaise des consommateurs')}.`)),
        s('delivery', '5. Organisation et participation', p('Les séances sont organisées via Calendly ou d’un commun accord. Nous cherchons raisonnablement à tenir compte de vos préférences.') + ul('Fournissez des informations exactes dans les formulaires et bilans.', 'Soyez à l’heure et participez au processus convenu.', 'Communiquez avec respect envers les coachs et participants.', 'Vérifiez les délais, langues et inclusions dans l’offre.') + p('L’enregistrement facultatif de l’appel découverte avec Fathom nécessite un accord explicite préalable. Vous pouvez participer sans enregistrement.')),
        s('limits', '6. Limites et responsabilité', p('Le coaching en communication et la formation sont éducatifs et destinés au développement personnel. Ils ne remplacent pas un traitement médical, psychologique ou thérapeutique. Un service clinique distinct nécessite ses propres informations et son contrat.', 'Les résultats dépendent notamment de votre situation, de votre participation et de votre pratique. Aucune progression de carrière, amélioration relationnelle ou autre résultat précis n’est garanti.', 'Les conditions existantes limitent les dommages indirects, accessoires et consécutifs et plafonnent la responsabilité au montant payé pour le service, seulement dans les limites autorisées par la loi. Rien ici n’exclut les responsabilités ou recours qui ne peuvent légalement être exclus. Ces limites doivent être examinées selon le service et le client.')),
        s('materials', '7. Supports et enregistrements', p('La notice existante attribue le cadre de communication, les supports, consignes, infographies et méthodes à Estève Pannetier, Jonas Pannetier et Anu Timmerbacka. Les contenus de tiers conservent leurs droits et licences.', '<strong>Usage personnel :</strong> téléchargement et utilisation à titre personnel et non commercial. Reproduction, distribution ou adaptation commerciale : autorisation écrite requise, sauf licence particulière différente.', '<strong>Enregistrements :</strong> un enregistrement convenu est réservé à votre relecture personnelle et ne peut être diffusé publiquement ou commercialement. Réserver n’autorise pas l’enregistrement d’autres participants.')),
        s('confidentiality', '8. Confidentialité', p('Les conversations, bilans et informations personnelles sont traités comme confidentiels. La prestation peut impliquer les coachs et prestataires de la <a href="/privacy">notice sur les données</a>, y compris les copies des courriels Scan à Estève et Anu.') + ul('Une communication peut être faite avec votre consentement explicite.', 'Elle peut être exigée par la loi ou une procédure légale.', 'Un risque de dommage imminent peut nécessiter une action adaptée dans les limites de la loi.', 'La recherche ou les témoignages nécessitent une autorisation et une anonymisation adaptée ; retirer un nom ne rend pas toujours un dossier anonyme.')),
        s('conduct', '9. Participation respectueuse', p('Harcèlement, discrimination, propos haineux, perturbations, violation de la confidentialité et usage illégal ne sont pas acceptables.', 'Les conditions existantes permettent de mettre fin au service et de refuser un remboursement en cas de violation, sous réserve du contrat et des droits impératifs. Cela ne crée pas une exemption automatique aux protections des consommateurs.')),
        s('law', '10. Droit et tribunaux', p('Les conditions existantes choisissent le droit finlandais et les tribunaux d’Helsinki, avec médiation si elle est convenue. Les protections et droits de compétence impératifs des consommateurs restent applicables ; tous les consommateurs ne sont pas obligés de saisir uniquement Helsinki.', 'Pour les services fournis en France, les protections françaises applicables doivent aussi être prises en compte. Les règles dépendent du vendeur, du lieu du client et du service.')),
        s('disputes', '11. Résoudre une difficulté', p(`Contactez ${email} pour expliquer le problème. Nous cherchons une solution par le dialogue. Une médiation peut être convenue, mais elle ne supprime pas le droit de consulter une autorité ou un tribunal.`)),
        s('updates', '12. Modifications', p('Les conditions peuvent évoluer avec les services ou la loi. Les changements importants seront annoncés par courriel ou sur le site. Pour une réservation existante, le contrat et le droit applicable déterminent les modifications possibles ; continuer à naviguer ne vaut ni renonciation aux droits ni acceptation automatique d’un contrat payant modifié.')),
      ],
    },
    '/cookies': {
      title: 'Cookies et vos choix', description: 'Gardez les fonctions essentielles. Choisissez si vous autorisez la mesure facultative des visites.',
      summary: ['Les cookies de connexion aident le service à fonctionner. Les bloquer peut empêcher l’accès au compte.', 'Google Analytics se charge seulement après acceptation, lorsque la mesure est activée sur le site de production.', 'Refuser la mesure laisse le site accessible. Vous pouvez changer d’avis à tout moment.', 'Le retrait arrête les futures mesures du site ; il n’efface pas les informations déjà reçues par Google.'],
      sections: [
        s('meaning', '1. Que sont les cookies ?', p('Ce sont de petits fichiers enregistrés sur votre appareil. Ils peuvent maintenir la connexion ou retenir une préférence. Le stockage local du navigateur est une autre manière de conserver un choix ; ce n’est pas un cookie.')),
        s('essential', '2. Cookies essentiels', p('Le cookie de session du site est <code>connect.sid</code>. Il maintient les sessions de compte et est configuré pour durer jusqu’à sept jours. Il est marqué HTTP-only, SameSite=Lax et sécurisé en production.', 'Vous pouvez le bloquer dans le navigateur, mais certaines fonctions comme rester connecté peuvent ne plus fonctionner. Les fonctions essentielles ne nécessitent pas l’acceptation de la mesure des visites.')),
        s('analytics', '3. Google Analytics facultatif', p('Lorsque la mesure est activée en production et acceptée, Google Analytics 4 mesure les visites et certains clics vers les demandes ou le paiement Scan, sur l’accueil, le Scan et les cinq pages de coaching IA. Un clic ne prouve pas une réservation ou un achat.') + ul('Aucune balise Google Analytics de ce site ne se charge avant acceptation ou après un refus initial.', 'Le site envoie le chemin public autorisé, la langue, une catégorie générale de provenance et certains libellés de clic. Google traite aussi les informations techniques de requête/appareil et les identifiants de cookies ; la mesure n’est pas anonyme.', 'La mesure exclut noms, courriels, identifiants d’achat, réponses aux questionnaires, scores, adresses de provenance complètes et paramètres d’URL.', 'Les pages privées, comptes, paiements, résultats et MyFive sont exclus. Les signaux publicitaires Google et la personnalisation des annonces sont désactivés.', 'Les cookies GA <code>_ga</code> et <code>_ga_*</code> expirent selon la configuration après 180 jours, sans renouvellement.', 'Votre choix Accepter/Refuser est enregistré dans le stockage local sous <code>ge.analytics-consent.v1</code> pour 180 jours. Si le stockage est bloqué, le choix peut ne durer que la visite.', 'Le retrait arrête les futures mesures, efface les cookies GA accessibles du site et recharge si nécessaire. Il n’efface pas l’historique chez le prestataire.') + p(`Consultez ${external(ga, 'les explications de Google')} et notre <a href="/privacy">notice sur les données</a>. Conservation dans le compte, contrats et transferts sont distincts de l’expiration dans le navigateur.`) + '<button type="button" class="policy-button" data-cookie-preferences>Modifier mon choix de cookies</button>'),
        s('third-parties', '4. Autres services et cookies', p('Le code de mesure du site n’active pas de cookies publicitaires ou de suivi des réseaux sociaux. Les autres services ont leurs propres pratiques et notices lorsque vous les utilisez.') + ul(`${external('https://stripe.com/privacy', 'Stripe')} : paiement et prévention de la fraude.`, `${external('https://calendly.com/privacy', 'Calendly')} : plateforme de réservation.`, `${external('https://www.typeform.com/privacy/', 'Typeform')} : technologies du questionnaire.`, `${external('https://policies.google.com/privacy', 'Google / YouTube')} : connexion ou vidéos intégrées lorsqu’utilisées.`, `${external('https://www.cloudflare.com/privacypolicy/', 'Cloudflare')} : diffusion et sécurité selon leur utilisation.`) + p('L’inventaire réel des cookies et le chargement des contenus intégrés nécessitent une vérification distincte. Refuser la mesure du site ne décrit pas tous les cookies du site propre d’un prestataire.')),
        s('manage', '5. Gérer les cookies dans le navigateur', p('Les réglages permettent de voir et supprimer les cookies, bloquer ceux de tiers ou de certains sites, ou les effacer à la fermeture. La navigation privée efface généralement ses données de session à la fermeture de toutes ses fenêtres ; elle ne rend pas anonyme.') + ul(external('https://support.google.com/chrome/answer/95647', 'Google Chrome'), external('https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop', 'Mozilla Firefox'), external('https://support.apple.com/guide/safari/manage-cookies-sfri11471/mac', 'Safari'), external('https://support.microsoft.com/en-us/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09', 'Microsoft Edge')) + p('Effacer les cookies et le stockage local peut supprimer votre choix enregistré. Utilisez « Choix des cookies » sur le site pour choisir à nouveau.')),
        s('rights', '6. Vos droits', p('Vous pouvez refuser la mesure non essentielle, retirer votre consentement et demander des informations. Effacer les cookies du navigateur ne supprime pas les données déjà détenues par un prestataire.', `Consultez la <a href="/privacy#rights">section sur vos droits</a> ou écrivez à ${email} pour les droits applicables d’accès, de suppression, d’opposition et de plainte.`)),
        s('updates', '7. Modifications', p('La notice peut évoluer avec l’usage des cookies. Un nouvel usage nécessitant un consentement doit faire l’objet d’une demande séparée. La date ci-dessous concerne cette notice, pas la vérification de tous les réglages des prestataires.')),
      ],
    },
  },
};

export function isPolicyPath(path: string): path is PolicyPath {
  return Object.hasOwn(POLICY_PAGES.en, path);
}

export function renderPolicyPage(path: PolicyPath, language: SiteLanguage): string {
  const copy = POLICY_PAGES[language][path];
  const fr = language === 'fr';
  const nav = Object.entries(POLICY_PAGES[language]).map(([href, item]) => `<a href="${href}"${href === path ? ' aria-current="page"' : ''}>${item.title}</a>`).join('');
  const contents = copy.sections.map(section => `<li><a href="#${section.id}">${section.title}</a></li>`).join('');
  const sections = copy.sections.map(section => `<section id="${section.id}" class="policy-section" aria-labelledby="${section.id}-title"><h2 id="${section.id}-title">${section.title}</h2>${section.body}</section>`).join('');
  return articleLinks(`<article class="policy-page" lang="${language}">
    <header class="policy-header"><div class="policy-wrap"><p class="policy-eyebrow">Green Elephant · ${fr ? 'Confiance et transparence' : 'Trust and transparency'}</p><h1${path === '/privacy' ? ' data-testid="text-privacy-title"' : ''}>${copy.title}</h1><p class="policy-intro">${copy.description}</p><p class="policy-meta">${fr ? 'Mise à jour du texte : 6 octobre 2026' : 'Copy updated: 6 October 2026'}</p></div></header>
    <div class="policy-wrap"><section class="policy-summary" aria-labelledby="policy-summary-title"><h2 id="policy-summary-title">${fr ? 'L’essentiel' : 'At a glance'}</h2>${ul(...copy.summary)}<a href="#policy-details">${fr ? 'Lire les informations complètes' : 'Read the full details'} ↓</a></section>
    <nav class="policy-contents" aria-label="${fr ? 'Sur cette page' : 'On this page'}"><h2>${fr ? 'Sur cette page' : 'On this page'}</h2><ol>${contents}</ol></nav>
    <div id="policy-details">${sections}</div>
    <aside class="policy-contact"><h2>${fr ? 'Une question ?' : 'Have a question?'}</h2><p>${fr ? 'Demandez une explication ou parlez-nous de votre préoccupation.' : 'Ask for an explanation or tell us about a concern.'}</p><a data-testid="link-privacy-email" href="mailto:esteve@greenelephant.org">esteve@greenelephant.org</a></aside>
    <nav class="policy-related" aria-label="${fr ? 'Autres politiques' : 'Related policies'}">${nav}</nav></div>
  </article>`, language);
}
